-- ══════════════════════════════════════════════════════════════════════════
-- STANDALONE BOOTSTRAP · STEP 2 of 3 — the CardOps migration history,
-- concatenated in order, with Master-Ops-only table chatter removed.
-- Run AFTER 00_foundations.sql and part 1.
-- Generated by scripts/build-bootstrap.mjs — do not hand-edit.
-- ══════════════════════════════════════════════════════════════════════════

-- ═══════════ 20260720160000_portfolio_snapshots.sql ═══════════
-- CardOps: daily portfolio snapshot — the history the value-over-time chart,
-- trend leaderboards, and velocity metrics all read from. One row per day,
-- written by the nightly pricing daemon. Additive + idempotent.
--
-- Start the clock early: history only accrues going forward, so this table
-- exists to begin collecting even before the chart UI matters.

create table if not exists public.card_portfolio_snapshots (
  snapshot_date date primary key,
  card_count    int not null default 0,
  cost_basis    numeric(14,2) not null default 0,   -- pool total + individual bases
  market_value  numeric(14,2) not null default 0,   -- sum of manual??market over live cards
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);
alter table public.card_portfolio_snapshots enable row level security;
-- Card users may read the history; the cron writes via service role (bypasses RLS).
drop policy if exists card_portfolio_snapshots_sel on public.card_portfolio_snapshots;
create policy card_portfolio_snapshots_sel on public.card_portfolio_snapshots
  for select to authenticated using (public.has_card_access());

-- ═══════════ 20260720180000_card_groups.sql ═══════════
-- CardOps: card GROUPS / folders — arbitrary named collections a card can
-- belong to (many at once), for organizing inventory however you like.
-- Distinct from lots (which are for selling). Additive + idempotent.

create table if not exists public.card_groups (
  id         uuid primary key default gen_random_uuid(),
  name       text not null,
  color      text,
  sort       int not null default 0,
  created_at timestamptz not null default now()
);
alter table public.card_groups enable row level security;
drop policy if exists card_groups_rw on public.card_groups;
create policy card_groups_rw on public.card_groups
  for all to authenticated
  using (public.has_card_access())
  with check (public.has_card_access());

create table if not exists public.card_group_items (
  group_id uuid not null references public.card_groups(id) on delete cascade,
  card_id  uuid not null references public.cards(id) on delete cascade,
  added_at timestamptz not null default now(),
  primary key (group_id, card_id)
);
create index if not exists card_group_items_card_idx on public.card_group_items (card_id);
alter table public.card_group_items enable row level security;
drop policy if exists card_group_items_rw on public.card_group_items;
create policy card_group_items_rw on public.card_group_items
  for all to authenticated
  using (public.has_card_access())
  with check (public.has_card_access());

-- ═══════════ 20260720200000_card_alerts.sql ═══════════
-- CardOps: price alerts / watchlist — watch a card for a target price. The
-- watchlist reads the current value live, so a crossing shows immediately
-- (push notifications on crossing are a later add). One alert per card.
-- Additive + idempotent.

create table if not exists public.card_alerts (
  card_id      uuid primary key references public.cards(id) on delete cascade,
  target_price numeric(12,2) not null,
  direction    text not null default 'above' check (direction in ('above','below')),
  note         text,
  created_at   timestamptz not null default now()
);
alter table public.card_alerts enable row level security;
drop policy if exists card_alerts_rw on public.card_alerts;
create policy card_alerts_rw on public.card_alerts
  for all to authenticated
  using (public.has_card_access())
  with check (public.has_card_access());

-- ═══════════ 20260720210000_card_alerts_notified.sql ═══════════
-- CardOps: price-alert push dedup — remember when we pushed a crossing so it
-- fires once per crossing (re-armed when the price goes back the other way).
-- Additive + idempotent.
alter table public.card_alerts add column if not exists notified_at timestamptz;

-- ═══════════ 20260720220000_card_source_quotes.sql ═══════════
-- Card source quotes (Beau, 2026-07-20): a per-source pricing layer that sits
-- ALONGSIDE realized sold-comps (card_comps). Each vendor — PriceCharting,
-- Scryfall, … — drops its CURRENT value(s) here so the card page can show every
-- source SEPARATELY and a blended consensus. Display-only guidance: nothing here
-- writes the authoritative cards.market_value (that stays comp-driven).
-- Additive + idempotent.

create table if not exists public.card_source_quotes (
  id uuid primary key default gen_random_uuid(),
  card_id uuid not null references public.cards(id) on delete cascade,
  source text not null,                  -- 'pricecharting' | 'scryfall' | …
  kind text not null default 'guide' check (kind in ('guide','sold')),
  grader text,                           -- null = raw / ungraded
  grade numeric(4,1),
  price numeric(12,2) not null,
  currency text not null default 'USD',
  label text,                            -- human tag, e.g. 'PSA 10', 'Ungraded · foil'
  url text,
  product_ref text,                      -- vendor product id, for stable re-fetch
  payload jsonb,
  fetched_at timestamptz not null default now(),
  -- one current row per (card, source, grade-slot): the upsert / dedupe target.
  slot text generated always as (
    source || ':' || coalesce(grader, 'RAW') || ':' ||
    coalesce(grade::text, 'raw') || ':' || coalesce(label, '')
  ) stored
);
create unique index if not exists card_source_quotes_slot_uniq
  on public.card_source_quotes (card_id, slot);
create index if not exists card_source_quotes_card_idx
  on public.card_source_quotes (card_id, source);

alter table public.card_source_quotes enable row level security;

-- RLS mirrors the card_* convention: any card-access user reads/writes; only the
-- owner deletes.
do $$ begin
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='card_source_quotes' and policyname='card_source_quotes_sel') then
    create policy card_source_quotes_sel on public.card_source_quotes
      for select to authenticated using (public.has_card_access());
  end if;
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='card_source_quotes' and policyname='card_source_quotes_ins') then
    create policy card_source_quotes_ins on public.card_source_quotes
      for insert to authenticated with check (public.has_card_access());
  end if;
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='card_source_quotes' and policyname='card_source_quotes_upd') then
    create policy card_source_quotes_upd on public.card_source_quotes
      for update to authenticated using (public.has_card_access()) with check (public.has_card_access());
  end if;
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='card_source_quotes' and policyname='card_source_quotes_del') then
    create policy card_source_quotes_del on public.card_source_quotes
      for delete to authenticated using (public.is_owner());
  end if;
end $$;

-- ═══════════ 20260720280000_cardops_sprint.sql ═══════════
-- CardOps sprint (Beau, 2026-07-20): %-move alerts, card news, shareable
-- showcases. Additive + idempotent. Paste once.

-- ── 1. %-move alerts ────────────────────────────────────────────────────────
-- Extend card_alerts so a watch can be a target price OR a percentage move over
-- a window. target_price becomes optional (a pct_move alert doesn't need one).
alter table public.card_alerts add column if not exists kind text not null default 'target'; -- 'target' | 'pct_move'
alter table public.card_alerts add column if not exists threshold_pct numeric;   -- pct_move: absolute % move that fires
alter table public.card_alerts add column if not exists window_days int;          -- pct_move: over this many days
alter table public.card_alerts alter column target_price drop not null;

-- ── 2. Card news ────────────────────────────────────────────────────────────
-- News items discovered for a card's subject (player / set / card name), scored
-- for significance + likely market direction. Shared inventory (has_card_access).
create table if not exists public.card_news (
  id uuid primary key default gen_random_uuid(),
  subject text not null,
  card_id uuid references public.cards(id) on delete set null,
  title text not null,
  url text not null,
  source text,
  published_at timestamptz,
  significance numeric,               -- 0..1 (AI)
  direction text,                     -- 'up' | 'down' | 'neutral'
  market_moving boolean not null default false,
  summary text,
  notified boolean not null default false,
  created_at timestamptz not null default now(),
  unique (url)
);
create index if not exists card_news_rank_idx on public.card_news (significance desc nulls last, created_at desc);
create index if not exists card_news_card_idx on public.card_news (card_id, created_at desc);

alter table public.card_news enable row level security;
do $$ begin
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='card_news' and policyname='card_news_read') then
    create policy card_news_read on public.card_news for select to authenticated using (public.has_card_access());
  end if;
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='card_news' and policyname='card_news_write_owner') then
    create policy card_news_write_owner on public.card_news for all to authenticated using (public.is_owner()) with check (public.is_owner());
  end if;
end $$;

-- ── 3. Shareable showcases ──────────────────────────────────────────────────
-- A public, link-shareable gallery of chosen cards. The public page reads via
-- the service role (by token); RLS here only governs the owner's management.
create table if not exists public.card_showcases (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  token text not null unique,
  title text not null default 'My Showcase',
  card_ids uuid[] not null default '{}',
  show_prices boolean not null default true,
  for_sale boolean not null default false,
  is_public boolean not null default true,
  contact text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists card_showcases_user_idx on public.card_showcases (user_id, created_at desc);

alter table public.card_showcases enable row level security;
do $$ begin
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='card_showcases' and policyname='card_showcases_rw_self') then
    create policy card_showcases_rw_self on public.card_showcases
      for all to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid());
  end if;
end $$;

-- ═══════════ 20260720290000_journal.sql ═══════════
-- Canonical internal journal (Beau, 2026-07-20). The generic double-entry ledger
-- CardOps posts INTO — and any future asset module (properties, machines) can post
-- to the same table. Each business event (a card sale, later a purchase) writes
-- balanced debit/credit lines tagged by entity + source. This is the internal book
-- of record that a later, gated Zoho/QBO push reads from. Owner-only. Idempotent.

create table if not exists public.journal_entries (
  id uuid primary key default gen_random_uuid(),
  entity_id uuid references public.entities(id) on delete set null,
  entry_date date not null,
  source text not null,        -- 'card_sale' | 'card_purchase' | …
  source_ref text not null,    -- the originating row's id (e.g. card_sales.id)
  line int not null default 0, -- ordering within one entry
  account text not null,       -- internal chart: cash, sales_revenue, platform_fees, shipping_expense, cogs, inventory, …
  debit numeric(12,2) not null default 0,
  credit numeric(12,2) not null default 0,
  memo text,
  created_at timestamptz not null default now()
);
create index if not exists journal_entries_source_idx on public.journal_entries (source, source_ref);
create index if not exists journal_entries_entity_idx on public.journal_entries (entity_id, entry_date);

alter table public.journal_entries enable row level security;
do $$ begin
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='journal_entries' and policyname='journal_entries_owner') then
    create policy journal_entries_owner on public.journal_entries
      for all to authenticated using (public.is_owner()) with check (public.is_owner());
  end if;
end $$;

-- ═══════════ 20260721000000_card_tax_treatment.sql ═══════════
-- Per-card tax classification (Beau, 2026-07-21). How a card is booked depends on
-- whether it's held as dealer inventory, a capital investment, or a hobby item —
-- each posts to the books differently. Per-card (versatile: a mixed collection can
-- hold some of each). Defaults to 'dealer' (matches the current journal). Additive.
alter table public.cards
  add column if not exists tax_treatment text not null default 'dealer';

do $$ begin
  if not exists (
    select 1 from information_schema.constraint_column_usage
    where table_name = 'cards' and constraint_name = 'cards_tax_treatment_chk'
  ) then
    alter table public.cards
      add constraint cards_tax_treatment_chk check (tax_treatment in ('dealer', 'investment', 'hobby'));
  end if;
end $$;

-- ═══════════ 20260721010000_card_receipts.sql ═══════════
-- Card cost receipts + intercompany advances (Beau, 2026-07-21). Each receipt is
-- either the paying entity's own purchase (its pool or specific cards) or an
-- ADVANCE to an affiliate — where the receiving company then decides how IT books
-- the money (pool basis or specific purchases). Owner-only (business bookkeeping).
-- The double-entry lands in journal_entries; this table is the source record.
create table if not exists public.card_receipts (
  id uuid primary key default gen_random_uuid(),
  entity_id uuid references public.entities(id) on delete set null,   -- who paid
  receipt_date date not null default current_date,
  vendor text,
  amount numeric(12,2) not null,
  image_path text,                    -- optional stored image (receipts bucket)
  note text,
  disposition text not null check (disposition in ('pool', 'cards', 'advance')),
  card_ids uuid[] not null default '{}',                              -- for 'cards'
  to_entity_id uuid references public.entities(id) on delete set null, -- for 'advance': the affiliate
  advance_disposition text check (advance_disposition in ('pool', 'cards')), -- how the receiver books it
  posted boolean not null default false,                              -- journal entries generated?
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists card_receipts_entity_idx on public.card_receipts (entity_id, receipt_date desc);

alter table public.card_receipts enable row level security;
do $$ begin
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='card_receipts' and policyname='card_receipts_owner') then
    create policy card_receipts_owner on public.card_receipts
      for all to authenticated using (public.is_owner()) with check (public.is_owner());
  end if;
end $$;

-- ═══════════ 20260721020000_receipt_treatment.sql ═══════════
-- Receipt tax treatment (Beau, 2026-07-21). A cost receipt/transaction is booked
-- under an entity AND a tax treatment (investment / dealer / hobby). For an
-- advance, the RECEIVING entity's treatment (the second transaction bar) is
-- captured separately. treatment = how the acquiring side holds these cards.
-- Additive + idempotent.
alter table public.card_receipts add column if not exists treatment text not null default 'dealer';
alter table public.card_receipts add column if not exists advance_treatment text;

do $$ begin
  if not exists (select 1 from information_schema.constraint_column_usage
                 where table_name='card_receipts' and constraint_name='card_receipts_treatment_chk') then
    alter table public.card_receipts add constraint card_receipts_treatment_chk
      check (treatment in ('dealer', 'investment', 'hobby'));
  end if;
  if not exists (select 1 from information_schema.constraint_column_usage
                 where table_name='card_receipts' and constraint_name='card_receipts_advance_treatment_chk') then
    alter table public.card_receipts add constraint card_receipts_advance_treatment_chk
      check (advance_treatment is null or advance_treatment in ('dealer', 'investment', 'hobby'));
  end if;
end $$;

-- ═══════════ 20260722000000_estimates_credits.sql ═══════════
-- Pricing intelligence: estimate cache + credit metering (Beau, 2026-07-22).
-- card_estimates caches each AI estimate (so viewing it again is free); credit_ledger
-- is the metered-compute account (managed model: each run debits the user). Additive
-- + idempotent.

create table if not exists public.card_estimates (
  id uuid primary key default gen_random_uuid(),
  card_id uuid not null references public.cards(id) on delete cascade,
  mode text not null check (mode in ('standard_plus', 'all_sales_plus')),
  value numeric(12,2),
  low numeric(12,2),
  high numeric(12,2),
  confidence text,
  rationale text,
  sources jsonb,               -- what data it used (own-sales stats, comparables, sample, flags)
  credits_spent integer not null default 0,
  model text,
  created_by uuid,
  created_at timestamptz not null default now()
);
create index if not exists card_estimates_card_idx on public.card_estimates (card_id, mode, created_at desc);

alter table public.card_estimates enable row level security;
do $$ begin
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='card_estimates' and policyname='card_estimates_all') then
    create policy card_estimates_all on public.card_estimates for all to authenticated
      using (public.has_card_access()) with check (public.has_card_access());
  end if;
end $$;

-- Metered-compute ledger. Balance = sum(delta). Positive = granted/purchased,
-- negative = spent. Written server-side (service role); users read their own.
create table if not exists public.credit_ledger (
  id bigint generated always as identity primary key,
  user_id uuid not null,
  delta integer not null,
  reason text,
  ref uuid,
  created_at timestamptz not null default now()
);
create index if not exists credit_ledger_user_idx on public.credit_ledger (user_id, created_at desc);

alter table public.credit_ledger enable row level security;
do $$ begin
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='credit_ledger' and policyname='credit_ledger_self_read') then
    create policy credit_ledger_self_read on public.credit_ledger for select to authenticated
      using (user_id = auth.uid());
  end if;
end $$;

-- O(1) balance for the signed-in user (SQL sum, not a client-side fetch-and-add).
create or replace function public.credit_balance()
returns integer language sql stable security definer set search_path = public as $$
  select coalesce(sum(delta), 0)::int from public.credit_ledger where user_id = auth.uid();
$$;
revoke all on function public.credit_balance() from public;
grant execute on function public.credit_balance() to authenticated;

-- ═══════════ 20260723000000_market_sales.sql ═══════════
-- Observed market sales history (Beau, 2026-07-23). The Card API free tier only
-- shows a ~3-day window; by storing each day's sales here (deduped), we build up a
-- full price-over-time history ourselves. Feeds the estimate engine + the card
-- sparkline. Additive + idempotent.
create table if not exists public.card_market_sales (
  id uuid primary key default gen_random_uuid(),
  card_id uuid not null references public.cards(id) on delete cascade,
  source text not null default 'thecardapi',
  external_id text,                 -- the platform listing/sale id (dedup key)
  title text,
  price numeric(12,2) not null,
  currency text default 'USD',
  grader text,
  grade numeric(4,1),
  platform text,                    -- ebay, tcgplayer, goldin, ...
  sold_at date,
  raw jsonb,
  seen_at timestamptz not null default now()
);
-- One row per (card, source, sale) — re-seeing a sale is a no-op.
create unique index if not exists card_market_sales_dedup on public.card_market_sales (card_id, source, external_id);
create index if not exists card_market_sales_card_idx on public.card_market_sales (card_id, sold_at desc);

alter table public.card_market_sales enable row level security;
do $$ begin
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='card_market_sales' and policyname='card_market_sales_all') then
    create policy card_market_sales_all on public.card_market_sales for all to authenticated
      using (public.has_card_access()) with check (public.has_card_access());
  end if;
end $$;

-- Per-card toggle: whether the daily job keeps accumulating its sales history.
alter table public.cards add column if not exists track_history boolean not null default true;

-- ═══════════ 20260724000000_multi_tenant_cards.sql ═══════════
-- Multi-tenant CardOps (Beau, 2026-07-23). Each user gets their OWN card inventory:
-- cards gains an owner (user_id, defaulting to the creator), and every card-scoped
-- table is isolated to that owner. The owner (Beau) is unlimited; other users are
-- capped at 100 NEW cards per day. The public showcase reads via the service role,
-- so per-user RLS does NOT affect public browsing. Additive + idempotent; all
-- existing inventory is backfilled to the owner.
--
-- Model: has_card_access() still gates entry to the CardOps app; user_id scopes
-- WHICH cards you see. A promoted card user starts with an empty inventory.

-- Owner's auth id (all existing rows belong to Beau).
-- ── 1) cards: owner column + default + backfill + index ──────────────────────
alter table public.cards add column if not exists user_id uuid;
alter table public.cards add column if not exists created_at timestamptz not null default now();
update public.cards set user_id = (select id from auth.users where email = 'bowmansx@gmail.com') where user_id is null;
alter table public.cards alter column user_id set default auth.uid();
do $$ begin
  if not exists (select 1 from public.cards where user_id is null) then
    alter table public.cards alter column user_id set not null;
  end if;
end $$;
create index if not exists cards_user_idx on public.cards (user_id);
create index if not exists cards_user_created_idx on public.cards (user_id, created_at);

-- ── 2) ownership helper ──────────────────────────────────────────────────────
create or replace function public.owns_card(p_card uuid)
returns boolean language sql stable security definer set search_path = public as $$
  select exists (select 1 from public.cards where id = p_card and user_id = auth.uid());
$$;
revoke all on function public.owns_card(uuid) from public;
grant execute on function public.owns_card(uuid) to authenticated;

-- ── 3) cards RLS: app-entry gate AND own the row ─────────────────────────────
do $$ declare pol text; begin
  for pol in select policyname from pg_policies where schemaname='public' and tablename='cards' loop
    execute format('drop policy %I on public.cards', pol);
  end loop;
  create policy cards_own on public.cards for all to authenticated
    using (public.has_card_access() and user_id = auth.uid())
    with check (public.has_card_access() and user_id = auth.uid());
end $$;

-- ── 4) every card_id child → isolated to the card's owner ────────────────────
do $$
declare t text; pol text;
  tabs text[] := array['card_alerts','card_comps','card_estimates','card_flag_events','card_grading_submissions','card_group_items','card_intake_items','card_lot_items','card_market_sales','card_photos','card_price_history','card_source_quotes','card_valuations'];
begin
  foreach t in array tabs loop
    if exists (select 1 from information_schema.tables where table_schema='public' and table_name=t) then
      execute format('alter table public.%I enable row level security', t);
      for pol in select policyname from pg_policies where schemaname='public' and tablename=t loop
        execute format('drop policy %I on public.%I', pol, t);
      end loop;
      execute format('create policy %I on public.%I for all to authenticated using (public.owns_card(card_id)) with check (public.owns_card(card_id))', t||'_own', t);
    end if;
  end loop;
end $$;

-- ── 5) rootless card-scoped tables → their own owner column, per-user ────────
do $$
declare t text; pol text;
  tabs text[] := array['card_groups','card_lots','card_watchlist','card_intake_sessions','card_import_batches','card_import_staging','card_portfolio_snapshots','card_format_profiles','card_storage_locations'];
begin
  foreach t in array tabs loop
    if exists (select 1 from information_schema.tables where table_schema='public' and table_name=t) then
      execute format('alter table public.%I add column if not exists user_id uuid', t);
      execute format('update public.%I set user_id = (select id from auth.users where email = ''bowmansx@gmail.com'') where user_id is null', t);
      execute format('alter table public.%I alter column user_id set default auth.uid()', t);
      execute format('alter table public.%I enable row level security', t);
      for pol in select policyname from pg_policies where schemaname='public' and tablename=t loop
        execute format('drop policy %I on public.%I', pol, t);
      end loop;
      execute format('create policy %I on public.%I for all to authenticated using (user_id = auth.uid()) with check (user_id = auth.uid())', t||'_own', t);
    end if;
  end loop;
end $$;

-- ── 6) 100 NEW cards per DAY for non-owners (owner unlimited) ─────────────────
-- AFTER STATEMENT so a single multi-row INSERT can't slip past a per-row count
-- (the just-inserted rows are visible here); rolls back the whole statement.
create or replace function public.enforce_daily_card_cap()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  if not public.is_owner() then
    if (select count(*) from public.cards where user_id = auth.uid() and created_at >= date_trunc('day', now())) > 100 then
      raise exception 'Daily limit reached: up to 100 new cards per day.';
    end if;
  end if;
  return null;
end $$;
drop trigger if exists trg_daily_card_cap on public.cards;
create trigger trg_daily_card_cap after insert on public.cards
  for each statement execute function public.enforce_daily_card_cap();

-- ── 7) card_pool per-user (SELECT-only) + pool ownership helper + ledger ─────
-- card_pool + its ledger are per-user, but SELECT-only for users — WRITES happen
-- only through the SECURITY DEFINER RPCs (which bypass RLS), preserving the
-- basis-integrity invariant (no hand-edited cost basis). The user_id column is
-- added FIRST because owns_pool() is a language-sql function validated at create.
alter table public.card_pool add column if not exists user_id uuid;
update public.card_pool set user_id = (select id from auth.users where email = 'bowmansx@gmail.com') where user_id is null;
alter table public.card_pool alter column user_id set default auth.uid();
create unique index if not exists card_pool_user_name_uniq on public.card_pool (user_id, name);

create or replace function public.owns_pool(p_pool uuid)
returns boolean language sql stable security definer set search_path = public as $$
  select exists (select 1 from public.card_pool where id = p_pool and user_id = auth.uid());
$$;
revoke all on function public.owns_pool(uuid) from public;
grant execute on function public.owns_pool(uuid) to authenticated;

alter table public.card_pool enable row level security;
do $$ declare pol text; begin
  for pol in select policyname from pg_policies where schemaname='public' and tablename='card_pool' loop
    execute format('drop policy %I on public.card_pool', pol);
  end loop;
  create policy card_pool_sel on public.card_pool for select to authenticated using (user_id = auth.uid());
end $$;

do $$ declare pol text; begin
  if exists (select 1 from information_schema.tables where table_schema='public' and table_name='card_pool_adjustments') then
    execute 'alter table public.card_pool_adjustments enable row level security';
    for pol in select policyname from pg_policies where schemaname='public' and tablename='card_pool_adjustments' loop
      execute format('drop policy %I on public.card_pool_adjustments', pol);
    end loop;
    create policy card_pool_adjustments_sel on public.card_pool_adjustments for select to authenticated
      using (public.owns_pool(pool_id));
  end if;
end $$;

-- card_news: market/player news is shared context, not private inventory (and
-- player/set items carry a null card_id) — keep a shared read for everyone.
do $$ declare pol text; begin
  if exists (select 1 from information_schema.tables where table_schema='public' and table_name='card_news') then
    execute 'alter table public.card_news enable row level security';
    for pol in select policyname from pg_policies where schemaname='public' and tablename='card_news' loop
      execute format('drop policy %I on public.card_news', pol);
    end loop;
    create policy card_news_read on public.card_news for select to authenticated using (public.has_card_access());
  end if;
end $$;

-- ── 8) per-user pools in the SECURITY DEFINER RPCs ───────────────────────────
-- These bypass RLS, so they must scope the pool to the caller/card owner
-- themselves — otherwise every user's lot would land in the owner's pool.

-- Speed Book: book a lot into the CALLER's own 'main' pool (lazily created).
create or replace function public.speed_book_commit(p_items jsonb, p_lot_cost numeric)
returns jsonb language plpgsql security definer set search_path = public as $$
declare
  v_pool   public.card_pool%rowtype;
  v_item   jsonb; v_cat text; v_year int := extract(year from now())::int;
  v_prefix text; v_seq int; v_sku text; v_id uuid; v_ids uuid[] := '{}'; v_n int := 0;
begin
  if not public.has_card_access() then raise exception 'forbidden'; end if;
  if p_lot_cost is null or p_lot_cost <= 0 then raise exception 'lot cost required'; end if;
  if p_items is null or jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items) = 0 then raise exception 'no items'; end if;

  -- The caller's own pool (create one on first use), locked to serialize batches.
  -- on-conflict + re-select handles a concurrent first-use without a duplicate pool.
  select * into v_pool from public.card_pool where name = 'main' and user_id = auth.uid() for update;
  if not found then
    insert into public.card_pool (name, user_id, total_cost, card_count) values ('main', auth.uid(), 0, 0)
      on conflict (user_id, name) do nothing;
    select * into v_pool from public.card_pool where name = 'main' and user_id = auth.uid() for update;
  end if;

  for v_item in select value from jsonb_array_elements(p_items) loop
    v_cat := coalesce(nullif(v_item->>'cat', ''), 'OT');
    v_prefix := v_cat || '-' || v_year || '-';
    loop
      select coalesce(max(substring(sku from char_length(v_prefix) + 1)::int), 0) + 1 into v_seq
        from public.cards where sku like v_prefix || '%';
      v_sku := v_prefix || lpad(v_seq::text, 6, '0');
      begin
        insert into public.cards (sku, entity_id, sport_category, zone, quick_booked, use_pool_basis, status)
        values (v_sku,
          case when public.is_owner() then 'bfa6ad79-0d3a-412b-a682-603aa9d23f1d'::uuid else null end,
          nullif(v_item->>'sport_category', ''), coalesce(nullif(v_item->>'zone', ''), 'BULK'),
          true, true, 'booked')
        returning id into v_id;
        exit;
      exception when unique_violation then end;
    end loop;
    v_ids := array_append(v_ids, v_id); v_n := v_n + 1;
  end loop;

  insert into public.card_pool_adjustments (pool_id, kind, amount, total_after, count_after, actor, note)
  values (v_pool.id, 'add', p_lot_cost, v_pool.total_cost + p_lot_cost, v_pool.card_count + v_n,
          coalesce(auth.uid()::text, 'system'), 'Speed Book lot of ' || v_n);
  update public.card_pool set total_cost = total_cost + p_lot_cost, card_count = card_count + v_n where id = v_pool.id;

  return jsonb_build_object('inserted', v_n, 'ids', to_jsonb(v_ids), 'pool_total', v_pool.total_cost + p_lot_cost);
end $$;

-- Sale: draw from the CARD OWNER's pool, and only for a card the caller owns.
create or replace function public.card_sell(
  p_card_id uuid, p_platform text, p_sale_price numeric, p_fees numeric,
  p_ship_income numeric, p_ship_cost numeric, p_order_ref text)
returns jsonb language plpgsql security definer set search_path = public as $$
declare
  v_card public.cards%rowtype; v_pool public.card_pool%rowtype;
  v_basis numeric := 0; v_net numeric; v_pl numeric;
begin
  if not (public.owns_card(p_card_id) or auth.role() = 'service_role') then raise exception 'forbidden'; end if;

  select * into v_card from public.cards where id = p_card_id for update;
  if not found then raise exception 'card not found'; end if;
  if v_card.status = 'sold' then raise exception 'card already sold'; end if;
  if p_sale_price is null or p_sale_price < 0 then raise exception 'sale price required'; end if;

  v_net := coalesce(p_sale_price, 0) - coalesce(p_fees, 0) + coalesce(p_ship_income, 0) - coalesce(p_ship_cost, 0);

  if v_card.use_pool_basis then
    select * into v_pool from public.card_pool where name = 'main' and user_id = v_card.user_id for update;
    if found and v_pool.card_count > 0 then
      v_basis := round(v_pool.total_cost / v_pool.card_count, 2);
      insert into public.card_pool_adjustments (pool_id, kind, card_id, amount, total_after, count_after, actor, note)
      values (v_pool.id, 'draw', p_card_id, -v_basis, v_pool.total_cost - v_basis, v_pool.card_count - 1,
              coalesce(auth.uid()::text, 'system'), 'Sale draw');
      update public.card_pool set total_cost = total_cost - v_basis, card_count = card_count - 1 where id = v_pool.id;
    end if;
  else
    v_basis := coalesce(v_card.individual_basis, 0);
  end if;

  v_pl := v_net - v_basis;
  perform set_config('cardops.in_sell', '1', true);

  insert into public.card_sales
    (card_id, platform, sale_price, fees, shipping_income, shipping_cost, net_proceeds, basis_drawn, profit_loss, order_ref)
  values (p_card_id, p_platform, p_sale_price, p_fees, p_ship_income, p_ship_cost, v_net, v_basis, v_pl, p_order_ref);
  update public.cards set status = 'sold', sold_at = now(), basis_drawn = v_basis where id = p_card_id;

  return jsonb_build_object('net', v_net, 'basis', v_basis, 'profit_loss', v_pl);
end $$;

-- ── 9) card_sales: see your own; but only the owner or the card_sell RPC may
-- WRITE it (a direct non-owner insert would skip the pool draw) ──────────────
do $$ declare pol text; begin
  execute 'alter table public.card_sales enable row level security';
  for pol in select policyname from pg_policies where schemaname='public' and tablename='card_sales' loop
    execute format('drop policy %I on public.card_sales', pol);
  end loop;
  create policy card_sales_sel on public.card_sales for select to authenticated using (public.owns_card(card_id) or public.is_owner());
  create policy card_sales_ins on public.card_sales for insert to authenticated with check (public.is_owner());
  create policy card_sales_upd on public.card_sales for update to authenticated using (public.is_owner()) with check (public.is_owner());
  create policy card_sales_del on public.card_sales for delete to authenticated using (public.is_owner());
end $$;

-- NOTE (left intentionally shared/owner-scoped, not per-card-user):
--   card_grade_multipliers  → global grading config
--   card_pricing_strategies → pricing templates (built-ins shared; per-user custom is a later step)
--   card_receipts           → owner-only business bookkeeping (already owner-gated)
--   card_showcases          → already has user_id; public read is via the service role
-- FOLLOW-UP (not isolated by this migration): the card-photos STORAGE bucket still
--   uses has_card_access() on the files themselves (paths are random UUIDs). Scope
--   the bucket per-user before relying on photo privacy across tenants.

-- ═══════════ 20260725000000_card_businesses.sql ═══════════
-- Phase 1b: CardOps owns its businesses (Beau, 2026-07-24).
-- CardOps is becoming a standalone product, so it can't depend on MasterOps'
-- `entities` table. It gets its own per-user `card_businesses` — the thing a card
-- is attributed to, carrying the tax treatment and the bookkeeping connection
-- (zoho_books_org_id today, QuickBooks later).
--
-- The owner's existing entities are copied in WITH THEIR IDs PRESERVED, so every
-- existing card / receipt / journal attribution keeps working with zero data
-- migration; only the foreign keys are repointed.
-- (`journal_entries` is already CardOps-only — MasterOps never touches it.)
-- Additive + idempotent.

create table if not exists public.card_businesses (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null default auth.uid(),
  name text not null,
  short_code text not null,
  type text,                       -- llc / s_corp / personal / ...
  zoho_books_org_id text,          -- the bookkeeping connection target
  active boolean not null default true,
  created_at timestamptz not null default now()
);
create index if not exists card_businesses_user_idx on public.card_businesses (user_id);
create unique index if not exists card_businesses_user_code_uniq on public.card_businesses (user_id, short_code);

alter table public.card_businesses enable row level security;
do $$ begin
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='card_businesses' and policyname='card_businesses_own') then
    create policy card_businesses_own on public.card_businesses for all to authenticated
      using (user_id = auth.uid()) with check (user_id = auth.uid());
  end if;
end $$;

-- Seed the owner's businesses from entities, preserving ids (owner resolved from
-- profiles.role='owner', falling back to the known owner email).
insert into public.card_businesses (id, user_id, name, short_code, type, zoho_books_org_id, active)
select e.id,
       coalesce((select p.id from public.profiles p where p.role = 'owner' limit 1),
                (select u.id from auth.users u where u.email = 'bowmansx@gmail.com')),
       e.name, e.short_code, e.type, e.zoho_books_org_id, coalesce(e.active, true)
from public.entities e
where coalesce((select p.id from public.profiles p where p.role = 'owner' limit 1),
               (select u.id from auth.users u where u.email = 'bowmansx@gmail.com')) is not null
on conflict (id) do nothing;

-- Repoint every card-side FK from entities -> card_businesses. Safe because the
-- seed above preserved ids, so no reference is orphaned.
do $$
declare r record;
begin
  for r in
    select con.conname, cl.relname as tbl
    from pg_constraint con
    join pg_class cl on cl.oid = con.conrelid
    join pg_class ref on ref.oid = con.confrelid
    join pg_namespace n on n.oid = cl.relnamespace
    where con.contype = 'f' and n.nspname = 'public' and ref.relname = 'entities'
      and cl.relname in ('cards','card_pool','journal_entries','card_receipts')
  loop
    execute format('alter table public.%I drop constraint %I', r.tbl, r.conname);
  end loop;
end $$;

do $$ begin
  if not exists (select 1 from pg_constraint where conname = 'cards_business_fk') then
    alter table public.cards add constraint cards_business_fk
      foreign key (entity_id) references public.card_businesses(id);
  end if;
  if not exists (select 1 from pg_constraint where conname = 'card_pool_business_fk') then
    alter table public.card_pool add constraint card_pool_business_fk
      foreign key (entity_id) references public.card_businesses(id);
  end if;
  if not exists (select 1 from pg_constraint where conname = 'journal_entries_business_fk') then
    alter table public.journal_entries add constraint journal_entries_business_fk
      foreign key (entity_id) references public.card_businesses(id) on delete set null;
  end if;
  if not exists (select 1 from pg_constraint where conname = 'card_receipts_business_fk') then
    alter table public.card_receipts add constraint card_receipts_business_fk
      foreign key (entity_id) references public.card_businesses(id) on delete set null;
  end if;
  if not exists (select 1 from pg_constraint where conname = 'card_receipts_to_business_fk') then
    alter table public.card_receipts add constraint card_receipts_to_business_fk
      foreign key (to_entity_id) references public.card_businesses(id) on delete set null;
  end if;
end $$;

-- ═══════════ 20260726000000_card_account_map.sql ═══════════
-- CardOps connector mapping (Beau, 2026-07-24). Each business picks which
-- bookkeeping app it syncs to, and maps CardOps' internal account keys to that
-- app's real accounts. Per-business so one user can run different books per
-- company (and a CardOps-only customer can point at QuickBooks instead).
-- Additive + idempotent.

-- Which backend this business syncs to: null = none (CardOps' own books only).
alter table public.card_businesses add column if not exists connector text;

create table if not exists public.card_account_map (
  id uuid primary key default gen_random_uuid(),
  business_id uuid not null references public.card_businesses(id) on delete cascade,
  provider text not null default 'zoho',
  account_key text not null,              -- ours: inventory, cash, cogs, ...
  external_account_id text not null,      -- theirs
  external_account_name text,
  updated_at timestamptz not null default now()
);
create unique index if not exists card_account_map_uniq
  on public.card_account_map (business_id, provider, account_key);
create index if not exists card_account_map_biz_idx on public.card_account_map (business_id);

alter table public.card_account_map enable row level security;
do $$ begin
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='card_account_map' and policyname='card_account_map_own') then
    create policy card_account_map_own on public.card_account_map for all to authenticated
      using (exists (select 1 from public.card_businesses b where b.id = business_id and b.user_id = auth.uid()))
      with check (exists (select 1 from public.card_businesses b where b.id = business_id and b.user_id = auth.uid()));
  end if;
end $$;

-- ═══════════ 20260727000000_card_push_log.sql ═══════════
-- Connector push log (Beau, 2026-07-24). The idempotency record: one row per
-- entry successfully posted to a bookkeeping app. The push endpoint skips any
-- entry already logged, so re-running a push can never duplicate a journal in
-- someone's real books. Additive + idempotent.
create table if not exists public.card_push_log (
  id uuid primary key default gen_random_uuid(),
  business_id uuid not null references public.card_businesses(id) on delete cascade,
  provider text not null,
  reference text not null,        -- our CARDOPS-... reference = the idempotency key
  external_id text,               -- their journal id, when returned
  pushed_at timestamptz not null default now(),
  pushed_by uuid
);
-- The guarantee: one successful post per (business, backend, entry).
create unique index if not exists card_push_log_uniq
  on public.card_push_log (business_id, provider, reference);
create index if not exists card_push_log_biz_idx on public.card_push_log (business_id, pushed_at desc);

alter table public.card_push_log enable row level security;
do $$ begin
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='card_push_log' and policyname='card_push_log_own') then
    create policy card_push_log_own on public.card_push_log for all to authenticated
      using (exists (select 1 from public.card_businesses b where b.id = business_id and b.user_id = auth.uid()))
      with check (exists (select 1 from public.card_businesses b where b.id = business_id and b.user_id = auth.uid()));
  end if;
end $$;

-- ═══════════ 20260728000000_multitenant_hardening.sql ═══════════
-- Multi-tenant hardening (Beau, 2026-07-24). The follow-ups flagged when CardOps
-- went multi-tenant — all of them only bite once a SECOND user exists, so they're
-- being closed before any invites go out. Additive + idempotent.
--
--   1. card-photos storage: the FILES weren't per-user (only their metadata was)
--   2. pricing templates: shared, so one user could edit/delete another's
--   3. grade multipliers: global config any card user could rewrite
--   4. two globally-unique names that a second user would collide with

-- ── 1) card-photos: a user sees their own files, plus legacy files for cards they own
-- New uploads are foldered <user_id>/<card_id>/…; existing ones are <card_id>/…,
-- so both layouts are honoured without moving a single object.
create or replace function public.card_photo_visible(p_name text)
returns boolean language plpgsql stable security definer set search_path = public as $$
declare seg text; cid uuid;
begin
  if p_name is null then return false; end if;
  seg := split_part(p_name, '/', 1);
  if seg = auth.uid()::text then return true; end if;   -- new layout
  begin
    cid := seg::uuid;                                    -- legacy layout: <card_id>/…
  exception when others then
    return false;
  end;
  return public.owns_card(cid);
end $$;
revoke all on function public.card_photo_visible(text) from public;
grant execute on function public.card_photo_visible(text) to authenticated;

drop policy if exists card_photos_storage_rw on storage.objects;
create policy card_photos_storage_rw on storage.objects
  for all to authenticated
  using (bucket_id = 'card-photos' and public.card_photo_visible(name))
  with check (bucket_id = 'card-photos' and public.card_photo_visible(name));

-- ── 2) pricing templates: built-ins stay shared, custom formats become per-user
alter table public.card_pricing_strategies add column if not exists user_id uuid;
-- Anything that isn't a built-in seed belongs to the owner who made it.
update public.card_pricing_strategies
   set user_id = coalesce((select p.id from public.profiles p where p.role = 'owner' limit 1),
                          (select u.id from auth.users u where u.email = 'bowmansx@gmail.com'))
 where user_id is null
   and key not in ('standard','conservative','aggressive','hot','thin_market','manual_lock');
alter table public.card_pricing_strategies alter column user_id set default auth.uid();
create index if not exists card_pricing_strategies_user_idx on public.card_pricing_strategies (user_id);

alter table public.card_pricing_strategies enable row level security;
do $$ declare pol text; begin
  for pol in select policyname from pg_policies where schemaname='public' and tablename='card_pricing_strategies' loop
    execute format('drop policy %I on public.card_pricing_strategies', pol);
  end loop;
  -- Read: the shared built-ins (user_id null) + your own formats.
  create policy card_pricing_strategies_read on public.card_pricing_strategies for select to authenticated
    using (user_id is null or user_id = auth.uid());
  -- Write: only your own — nobody can edit or delete a built-in or someone else's.
  create policy card_pricing_strategies_ins on public.card_pricing_strategies for insert to authenticated
    with check (user_id = auth.uid());
  create policy card_pricing_strategies_upd on public.card_pricing_strategies for update to authenticated
    using (user_id = auth.uid()) with check (user_id = auth.uid());
  create policy card_pricing_strategies_del on public.card_pricing_strategies for delete to authenticated
    using (user_id = auth.uid());
end $$;

-- ── 3) grade multipliers: shared reference data, owner-maintained
alter table public.card_grade_multipliers enable row level security;
do $$ declare pol text; begin
  for pol in select policyname from pg_policies where schemaname='public' and tablename='card_grade_multipliers' loop
    execute format('drop policy %I on public.card_grade_multipliers', pol);
  end loop;
  create policy card_grade_multipliers_read on public.card_grade_multipliers for select to authenticated
    using (public.has_card_access());
  create policy card_grade_multipliers_write on public.card_grade_multipliers for all to authenticated
    using (public.is_owner()) with check (public.is_owner());
end $$;

-- ── 4) names that were globally unique now scope to the user
-- format profiles: drop the global unique on name, add (user_id, name)
do $$ declare c text; begin
  for c in
    select con.conname from pg_constraint con
    join pg_class cl on cl.oid = con.conrelid
    where cl.relname = 'card_format_profiles' and con.contype = 'u'
  loop
    execute format('alter table public.card_format_profiles drop constraint %I', c);
  end loop;
end $$;
create unique index if not exists card_format_profiles_user_name_uniq
  on public.card_format_profiles (user_id, name);

-- storage locations: PK was the bare name, so two users couldn't both have "Box 1".
-- Nothing references this table, so re-keying is safe.
do $$ declare pk text; begin
  if not exists (select 1 from public.card_storage_locations where user_id is null) then
    select con.conname into pk from pg_constraint con
      join pg_class cl on cl.oid = con.conrelid
      where cl.relname = 'card_storage_locations' and con.contype = 'p';
    if pk is not null and pk <> 'card_storage_locations_user_name_pk' then
      execute format('alter table public.card_storage_locations drop constraint %I', pk);
      alter table public.card_storage_locations alter column user_id set not null;
      alter table public.card_storage_locations add constraint card_storage_locations_user_name_pk primary key (user_id, name);
    end if;
  end if;
end $$;

-- ═══════════ 20260729000000_push_log_status.sql ═══════════
-- Push-log claim status (Beau, 2026-07-24). The push now CLAIMS an entry in this
-- table *before* posting it outward, so the unique index becomes a real lock that
-- fires before money moves (previously it only fired on the log write afterwards,
-- which is too late). Statuses:
--   pending   — claimed, post in flight
--   posted    — confirmed landed
--   uncertain — the request failed after being sent; we do NOT know if it landed,
--               so it is never auto-retried (a duplicate in real books is worse
--               than a missing one you can see and fix)
-- Additive + idempotent. Existing rows were only ever written on success.
alter table public.card_push_log add column if not exists status text not null default 'posted';
alter table public.card_push_log add column if not exists error text;
alter table public.card_push_log add column if not exists updated_at timestamptz not null default now();
create index if not exists card_push_log_status_idx on public.card_push_log (business_id, status);

-- ═══════════ 20260730000000_card_user_prefs.sql ═══════════
-- CardOps per-user preferences (Beau, 2026-07-24). Currently just the automatic
-- estimate policy: whether estimates run on their own, which of the two modes,
-- and at what model depth. Default is ON with the cheap model, as Beau specced.
-- Additive + idempotent.
create table if not exists public.card_user_prefs (
  user_id uuid primary key default auth.uid(),
  auto_estimate text not null default 'both',    -- off | A | B | both
  estimate_model text not null default 'light',  -- light (Haiku) | deep (Opus)
  updated_at timestamptz not null default now()
);
alter table public.card_user_prefs enable row level security;
do $$ begin
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='card_user_prefs' and policyname='card_user_prefs_own') then
    create policy card_user_prefs_own on public.card_user_prefs for all to authenticated
      using (user_id = auth.uid()) with check (user_id = auth.uid());
  end if;
end $$;

-- ═══════════ 20260731000000_daemon_multitenant.sql ═══════════
-- Daemon multi-tenancy fix (Beau, 2026-07-24).
--
-- 20260724000000_multi_tenant_cards.sql gave card_portfolio_snapshots a user_id
-- (default auth.uid()) and a `user_id = auth.uid()` RLS policy — but left the
-- PRIMARY KEY on snapshot_date alone. Two consequences, both live:
--
--   1. The nightly daemon writes via the SERVICE role, where auth.uid() is NULL,
--      so every snapshot written since that migration landed has user_id = NULL
--      and is INVISIBLE to the portfolio page (which reads under RLS). The NAV
--      chart has been silently frozen.
--   2. One row per DATE means one global snapshot, so a second user's inventory
--      would be summed into the same row rather than tracked separately.
--
-- Re-key to (user_id, snapshot_date): one snapshot per user per day.
-- Idempotent; safe to re-run.

-- ── 1) Adopt the orphaned service-written rows ───────────────────────────────
-- Give NULL-owner rows to the owner, but drop any whose date ALREADY has an
-- owner row (that date's owner row is the good one — the NULL row is the
-- service-written duplicate that nobody could see).
do $$
declare v_owner uuid;
begin
  select coalesce(
    (select id from public.profiles where role = 'owner' order by id limit 1),
    (select id from auth.users where email = 'bowmansx@gmail.com')
  ) into v_owner;
  if v_owner is null then return; end if;

  delete from public.card_portfolio_snapshots s
   where s.user_id is null
     and exists (
       select 1 from public.card_portfolio_snapshots o
        where o.snapshot_date = s.snapshot_date and o.user_id = v_owner
     );

  update public.card_portfolio_snapshots
     set user_id = v_owner
   where user_id is null;
end $$;

-- ── 2) Re-key: (user_id, snapshot_date) ──────────────────────────────────────
do $$
declare pk text;
begin
  -- Only proceed once every row has an owner, so the NOT NULL can't fail.
  if exists (select 1 from public.card_portfolio_snapshots where user_id is null) then
    raise notice 'card_portfolio_snapshots still has NULL user_id rows — skipping re-key';
    return;
  end if;

  select con.conname into pk
    from pg_constraint con
    join pg_class cl on cl.oid = con.conrelid
   where cl.relname = 'card_portfolio_snapshots' and con.contype = 'p';

  if pk is distinct from 'card_portfolio_snapshots_user_date_pk' then
    if pk is not null then
      execute format('alter table public.card_portfolio_snapshots drop constraint %I', pk);
    end if;
    alter table public.card_portfolio_snapshots alter column user_id set not null;
    alter table public.card_portfolio_snapshots
      add constraint card_portfolio_snapshots_user_date_pk primary key (user_id, snapshot_date);
  end if;
end $$;

create index if not exists card_portfolio_snapshots_user_date_idx
  on public.card_portfolio_snapshots (user_id, snapshot_date);

-- ═══════════ 20260732000000_per_user_sku.sql ═══════════
-- Per-user SKU namespace (Beau, 2026-07-24).
--
-- cards.sku has been `text unique not null` since 20260713150000_cardops_init.sql
-- (line 155) — a GLOBAL unique. The multi-tenant work re-keyed
-- card_format_profiles and card_storage_locations per user but missed this one.
--
-- Why that blocks every invite: nextSku() (src/lib/cards/skudb.ts) computes
-- max+1 from an RLS-SCOPED read, so a brand-new user with an empty inventory
-- always computes sequence 1 — e.g. BB-2026-000001 — which already exists on the
-- owner's row. The insert fails 23505, and the retry loop recomputes the SAME
-- sku, so it fails every time. A new card user cannot create a card in any
-- category+year the owner has already used, from /cards/new, /cards/intake, or
-- CSV import.
--
-- A SKU is a per-collection label, not a global identifier, so the correct key
-- is (user_id, sku). Idempotent; safe to re-run.

-- ── 1) Per-user uniqueness first, so we are never briefly unconstrained ──────
create unique index if not exists cards_user_sku_uniq on public.cards (user_id, sku);

-- ── 2) Drop the global unique (constraint or bare index, whichever it is) ────
do $$
declare c text;
begin
  -- The unique CONSTRAINT form.
  for c in
    select con.conname
      from pg_constraint con
      join pg_class cl on cl.oid = con.conrelid
      join pg_attribute a on a.attrelid = cl.oid and a.attnum = any (con.conkey)
     where cl.relname = 'cards'
       and con.contype = 'u'
       and array_length(con.conkey, 1) = 1
       and a.attname = 'sku'
  loop
    execute format('alter table public.cards drop constraint %I', c);
  end loop;

  -- The bare unique INDEX form (not backed by a constraint).
  for c in
    select i.relname
      from pg_index x
      join pg_class i on i.oid = x.indexrelid
      join pg_class t on t.oid = x.indrelid
      join pg_attribute a on a.attrelid = t.oid and a.attnum = x.indkey[0]
     where t.relname = 'cards'
       and x.indisunique
       and x.indnatts = 1
       and a.attname = 'sku'
       and i.relname <> 'cards_user_sku_uniq'
       and not exists (select 1 from pg_constraint con where con.conindid = i.oid)
  loop
    execute format('drop index public.%I', c);
  end loop;
end $$;

-- ── 3) Speed Book scans globally for the next sequence — scope it to the caller
-- so two users don't serialize against each other's numbering. Everything else
-- in this function is unchanged from 20260724000000.
create or replace function public.speed_book_commit(p_items jsonb, p_lot_cost numeric)
returns jsonb language plpgsql security definer set search_path = public as $$
declare
  v_pool   public.card_pool%rowtype;
  v_item   jsonb; v_cat text; v_year int := extract(year from now())::int;
  v_prefix text; v_seq int; v_sku text; v_id uuid; v_ids uuid[] := '{}'; v_n int := 0;
begin
  if not public.has_card_access() then raise exception 'forbidden'; end if;
  if p_lot_cost is null or p_lot_cost <= 0 then raise exception 'lot cost required'; end if;
  if p_items is null or jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items) = 0 then raise exception 'no items'; end if;

  select * into v_pool from public.card_pool where name = 'main' and user_id = auth.uid() for update;
  if not found then
    insert into public.card_pool (name, user_id, total_cost, card_count) values ('main', auth.uid(), 0, 0)
      on conflict (user_id, name) do nothing;
    select * into v_pool from public.card_pool where name = 'main' and user_id = auth.uid() for update;
  end if;

  for v_item in select value from jsonb_array_elements(p_items) loop
    v_cat := coalesce(nullif(v_item->>'cat', ''), 'OT');
    v_prefix := v_cat || '-' || v_year || '-';
    loop
      -- Scoped to the caller: SKUs are per-collection labels now.
      select coalesce(max(substring(sku from char_length(v_prefix) + 1)::int), 0) + 1 into v_seq
        from public.cards where sku like v_prefix || '%' and user_id = auth.uid();
      v_sku := v_prefix || lpad(v_seq::text, 6, '0');
      begin
        insert into public.cards (sku, entity_id, sport_category, zone, quick_booked, use_pool_basis, status)
        values (v_sku,
          case when public.is_owner() then 'bfa6ad79-0d3a-412b-a682-603aa9d23f1d'::uuid else null end,
          nullif(v_item->>'sport_category', ''), coalesce(nullif(v_item->>'zone', ''), 'BULK'),
          true, true, 'booked')
        returning id into v_id;
        exit;
      exception when unique_violation then end;
    end loop;
    v_ids := array_append(v_ids, v_id); v_n := v_n + 1;
  end loop;

  insert into public.card_pool_adjustments (pool_id, kind, amount, total_after, count_after, actor, note)
  values (v_pool.id, 'add', p_lot_cost, v_pool.total_cost + p_lot_cost, v_pool.card_count + v_n,
          coalesce(auth.uid()::text, 'system'), 'Speed Book lot of ' || v_n);
  update public.card_pool set total_cost = total_cost + p_lot_cost, card_count = card_count + v_n where id = v_pool.id;

  return jsonb_build_object('inserted', v_n, 'ids', to_jsonb(v_ids), 'pool_total', v_pool.total_cost + p_lot_cost);
end $$;
