-- ══════════════════════════════════════════════════════════════════════════
-- STANDALONE BOOTSTRAP · STEP 3 of 3 — the CardOps migration history,
-- concatenated in order, with Master-Ops-only table chatter removed.
-- Run AFTER 00_foundations.sql and part 2.
-- Generated by scripts/build-bootstrap.mjs — do not hand-edit.
-- ══════════════════════════════════════════════════════════════════════════

-- ═══════════ 20260733000000_card_sales_tenancy.sql ═══════════
-- card_sales tenancy + reversal rights (Beau, 2026-07-24).
--
-- Three gaps the multi-tenant pass left behind:
--
--  1. card_sales has no user_id, and its SELECT policy is
--     `owns_card(card_id) or is_owner()` — so the owner's every unfiltered read
--     returns EVERY user's sales (reports, ledger rebuild, tax insights).
--  2. The idempotency index is `unique (platform, order_ref)` GLOBALLY, while
--     order_ref is free text the seller types. Two users typing "1" or an
--     invoice number on platform 'ebay' collide: the second real sale is
--     rejected with a raw duplicate-key error naming a row RLS forbids them to
--     see. It is also an existence oracle over another user's order refs, and a
--     squatted real eBay order id makes the nightly sync classify the owner's
--     own settlement as "skipped" so that revenue never books.
--  3. card_sell was re-gated to owns_card() by the multi-tenant pass, but
--     card_unsell and card_lot_unsell were left on is_owner(). A card_ops user
--     can therefore SELL but never UN-SELL: one fat-fingered sale price strands
--     their pool basis and P/L permanently, because every other correction path
--     (guard_card_sale, card_sales UPDATE/DELETE, the select-only pool policies)
--     is also owner-gated. Those two functions ALSO never check that the card or
--     lot belongs to the caller.
--
-- Idempotent; safe to re-run.

-- ── 1) card_sales.user_id, backfilled from the card ─────────────────────────
alter table public.card_sales add column if not exists user_id uuid;
update public.card_sales s
   set user_id = c.user_id
  from public.cards c
 where c.id = s.card_id and s.user_id is null;
create index if not exists card_sales_user_idx on public.card_sales (user_id);

-- ── 2) Per-user idempotency namespace ───────────────────────────────────────
drop index if exists public.card_sales_platform_order_uq;
create unique index if not exists card_sales_user_platform_order_uq
  on public.card_sales (user_id, platform, order_ref)
  where order_ref is not null;

-- ── 3) card_sales is read by its owner, not by every owner ──────────────────
do $$ declare pol text; begin
  execute 'alter table public.card_sales enable row level security';
  for pol in select policyname from pg_policies where schemaname='public' and tablename='card_sales' loop
    execute format('drop policy %I on public.card_sales', pol);
  end loop;
  -- Fall back to the card's owner for any row a backfill couldn't reach.
  create policy card_sales_sel on public.card_sales for select to authenticated
    using (coalesce(user_id = auth.uid(), public.owns_card(card_id)));
  -- Writes still only through card_sell / card_unsell (SECURITY DEFINER), which
  -- keep the pool draw and the basis in step. A direct insert would skip that.
  create policy card_sales_ins on public.card_sales for insert to authenticated
    with check (public.is_owner());
  create policy card_sales_upd on public.card_sales for update to authenticated
    using (public.is_owner()) with check (public.is_owner());
  create policy card_sales_del on public.card_sales for delete to authenticated
    using (public.is_owner());
end $$;

-- ── 4) card_sell stamps the owner onto the sale ─────────────────────────────
-- Same body as 20260724000000 with only the card_sales insert amended.
create or replace function public.card_sell(
  p_card_id uuid, p_platform text, p_sale_price numeric, p_fees numeric,
  p_ship_income numeric, p_ship_cost numeric, p_order_ref text)
returns jsonb language plpgsql security definer set search_path = public as $$
declare
  v_card public.cards%rowtype; v_pool public.card_pool%rowtype;
  v_basis numeric := 0; v_net numeric; v_pl numeric;
begin
  if not (public.owns_card(p_card_id) or auth.role() = 'service_role') then raise exception 'forbidden'; end if;

  select * into v_card from public.cards where id = p_card_id for update;
  if not found then raise exception 'card not found'; end if;
  if v_card.status = 'sold' then raise exception 'card already sold'; end if;
  if p_sale_price is null or p_sale_price < 0 then raise exception 'sale price required'; end if;

  v_net := coalesce(p_sale_price, 0) - coalesce(p_fees, 0) + coalesce(p_ship_income, 0) - coalesce(p_ship_cost, 0);

  if v_card.use_pool_basis then
    select * into v_pool from public.card_pool where name = 'main' and user_id = v_card.user_id for update;
    if found and v_pool.card_count > 0 then
      v_basis := round(v_pool.total_cost / v_pool.card_count, 2);
      insert into public.card_pool_adjustments (pool_id, kind, card_id, amount, total_after, count_after, actor, note)
      values (v_pool.id, 'draw', p_card_id, -v_basis, v_pool.total_cost - v_basis, v_pool.card_count - 1,
              coalesce(auth.uid()::text, 'system'), 'Sale draw');
      update public.card_pool set total_cost = total_cost - v_basis, card_count = card_count - 1 where id = v_pool.id;
    end if;
  else
    v_basis := coalesce(v_card.individual_basis, 0);
  end if;

  v_pl := v_net - v_basis;
  perform set_config('cardops.in_sell', '1', true);

  insert into public.card_sales
    (card_id, user_id, platform, sale_price, fees, shipping_income, shipping_cost, net_proceeds, basis_drawn, profit_loss, order_ref)
  values (p_card_id, v_card.user_id, p_platform, p_sale_price, p_fees, p_ship_income, p_ship_cost, v_net, v_basis, v_pl, p_order_ref);
  update public.cards set status = 'sold', sold_at = now(), basis_drawn = v_basis where id = p_card_id;

  return jsonb_build_object('net', v_net, 'basis', v_basis, 'profit_loss', v_pl);
end $$;

-- ── 5) Whoever may sell a card may reverse that same card ───────────────────
-- Only the access check changes; the reversal body is untouched.
-- The rewrite is textual, so it MUST fail loudly if the source doesn't match —
-- a silent no-op here would leave the exact bug this migration exists to close.
do $$
declare
  src text;
  old_gate constant text := 'if not (public.is_owner() or auth.role() = ''service_role'') then';
begin
  select pg_get_functiondef(p.oid) into src
    from pg_proc p join pg_namespace n on n.oid = p.pronamespace
   where n.nspname = 'public' and p.proname = 'card_unsell';
  if src is null then
    raise notice 'card_unsell not present — skipping';
    return;
  end if;

  if position('public.owns_card(p_card_id)' in src) > 0 then
    raise notice 'card_unsell already scoped — skipping';
    return;
  end if;

  if position(old_gate in src) = 0 then
    raise exception 'card_unsell gate not found — refusing to leave it unscoped. Re-gate it by hand.';
  end if;

  -- is_owner() -> owns_card(p_card_id): a card_ops user may undo their OWN sale,
  -- and the owner may no longer silently reverse someone else's.
  execute replace(src, old_gate,
    'if not (public.owns_card(p_card_id) or auth.role() = ''service_role'') then');
end $$;

do $$
declare
  src text;
  old_gate constant text := 'if not (public.is_owner() or auth.role() = ''service_role'') then';
begin
  select pg_get_functiondef(p.oid) into src
    from pg_proc p join pg_namespace n on n.oid = p.pronamespace
   where n.nspname = 'public' and p.proname = 'card_lot_unsell';
  if src is null then
    raise notice 'card_lot_unsell not present — skipping';
    return;
  end if;

  if position('l.user_id = auth.uid()' in src) > 0 then
    raise notice 'card_lot_unsell already scoped — skipping';
    return;
  end if;

  if position(old_gate in src) = 0 then
    raise exception 'card_lot_unsell gate not found — refusing to leave it unscoped. Re-gate it by hand.';
  end if;

  execute replace(src, old_gate,
    'if not (exists (select 1 from public.card_lots l where l.id = p_lot_id and l.user_id = auth.uid())'
    || ' or auth.role() = ''service_role'') then');
end $$;

-- ═══════════ 20260734000000_status_is_a_transition.sql ═══════════
-- Status is a transition, not a field (foundation-fixes item 2).
--
-- The 2026-07-25 review's one CRITICAL: generic update paths accepted any
-- status, so an edit could pull a sold card back to 'booked' with no reversal
-- (basis stays drawn, sale row stays, card sellable AGAIN), and cards could be
-- created 'sold' with no sale booked. guard_card_sale only watched transitions
-- TO 'sold' and exempted the owner entirely.
--
-- New rule, enforced at the database so PostgREST can't route around it:
-- crossing the 'sold' boundary in EITHER direction — and any edit of
-- basis_drawn / sold_at — happens only inside card_sell / card_unsell (the
-- cardops.in_sell handshake). No owner exemption: the owner corrects mistakes
-- through card_unsell like everyone else. service_role is unaffected (crons
-- settle through the RPCs anyway). Non-sold status moves (booked/listed/
-- graded_out/archived) stay free.
--
-- Idempotent; safe to re-run.

create or replace function public.guard_card_sale()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  if (new.status is distinct from old.status
        and (new.status = 'sold' or old.status = 'sold'))
     or new.basis_drawn is distinct from old.basis_drawn
     or new.sold_at is distinct from old.sold_at then
    if coalesce(auth.role(), '') = 'authenticated'
       and coalesce(current_setting('cardops.in_sell', true), '') <> '1' then
      raise exception 'sold is a transition: use card_sell / card_unsell';
    end if;
  end if;
  return new;
end $$;
drop trigger if exists cards_sale_guard on public.cards;
create trigger cards_sale_guard before update on public.cards
  for each row execute function public.guard_card_sale();

-- Cards cannot be BORN sold: an insert with status='sold' has no sale row, no
-- basis draw, no P/L — it is a lie the books would repeat. Applies to every
-- authenticated insert (form, CSV import, raw PostgREST).
create or replace function public.guard_card_birth()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  if new.status = 'sold'
     and coalesce(auth.role(), '') = 'authenticated'
     and coalesce(current_setting('cardops.in_sell', true), '') <> '1' then
    raise exception 'cards cannot be created sold — import as booked and enter the sale explicitly';
  end if;
  return new;
end $$;
drop trigger if exists cards_birth_guard on public.cards;
create trigger cards_birth_guard before insert on public.cards
  for each row execute function public.guard_card_birth();

-- ═══════════ 20260735000000_purchase_lots.sql ═══════════
-- Purchase-lot basis (foundation-fixes item 3). DESTRUCTIVE by design.
--
-- The global card_pool answered "average cost of everything ever pooled" — it
-- cannot answer "which purchase, what cost", the first question in any audit,
-- and its default-on flag let unfunded cards dilute basis other cards funded
-- (the review's second CRITICAL). It is replaced by PURCHASE LOTS:
--
--   purchase_lots            one row per purchase EVENT (a box break, a
--                            collection buy): what it cost, when, from where,
--                            which tax bucket — immutable purchase record plus
--                            a mutable remaining_cost/remaining_count that
--                            draws consume.
--   purchase_lot_adjustments the append-only draw/correction trail (the same
--                            authoritative-ledger pattern card_pool used).
--   cards.purchase_lot_id    which purchase a card came from. Basis at sale:
--                            lot average of what REMAINS in that lot; a card
--                            with no lot uses individual_basis. No third path.
--
-- NAMING: "lot" was already taken by card_lots — those are SALE lots (bundle
-- cards into one listing) and are untouched. Purchase-side is purchase_lots
-- everywhere, including in code.
--
-- Zero sales exist (confirmed 2026-07-25), so there is no draw history to
-- carry. Any FUNDED pool balance still folds into a per-user "Legacy pool"
-- purchase lot before the drop — nothing is destroyed even if the pool turns
-- out to be non-empty. The verification SELECT below shows what the fold will
-- touch; review its output before continuing past it.

-- ── 0) verification: what exists right now ──────────────────────────────────
select 'card_pool rows' as what, count(*)::text as n from public.card_pool
union all
select 'funded pools (cost>0 or count>0)',
       count(*)::text from public.card_pool where total_cost > 0 or card_count > 0
union all
select 'pool adjustments', count(*)::text from public.card_pool_adjustments
union all
select 'cards flagged use_pool_basis', count(*)::text from public.cards where use_pool_basis
union all
select 'card_sales rows (expect 0)', count(*)::text from public.card_sales;

-- ── 1) the new tables ───────────────────────────────────────────────────────
create table if not exists public.purchase_lots (
  id              uuid primary key default gen_random_uuid(),
  user_id         uuid not null references auth.users(id),
  label           text,
  source          text,
  acquired_on     date not null default current_date,
  tax_bucket      text check (tax_bucket in ('investment','dealer','hobby') or tax_bucket is null),
  total_cost      numeric(14,2) not null check (total_cost >= 0),
  card_count      int not null check (card_count >= 0),
  remaining_cost  numeric(14,2) not null,
  remaining_count int not null,
  receipt_id      uuid references public.card_receipts(id),  -- books-side twin, when booked
  created_at      timestamptz not null default now()
);
create index if not exists purchase_lots_user_idx on public.purchase_lots (user_id);

create table if not exists public.purchase_lot_adjustments (
  id                    bigint generated always as identity primary key,
  lot_id                uuid not null references public.purchase_lots(id),
  ts                    timestamptz not null default now(),
  kind                  text not null check (kind in ('draw','correction','adjust')),
  card_id               uuid references public.cards(id),
  amount                numeric(12,2) not null,
  remaining_cost_after  numeric(14,2) not null,
  remaining_count_after int not null,
  actor                 text not null,
  note                  text
);
create index if not exists purchase_lot_adj_card_idx on public.purchase_lot_adjustments (card_id, kind, ts);

alter table public.cards add column if not exists purchase_lot_id uuid references public.purchase_lots(id);

-- RLS: each user sees and manages their own lots; the money columns are
-- RPC-only (trigger below), metadata stays freely editable.
alter table public.purchase_lots enable row level security;
drop policy if exists purchase_lots_own on public.purchase_lots;
create policy purchase_lots_own on public.purchase_lots
  for all to authenticated
  using (user_id = auth.uid()) with check (user_id = auth.uid());
alter table public.purchase_lot_adjustments enable row level security;
drop policy if exists purchase_lot_adj_sel on public.purchase_lot_adjustments;
create policy purchase_lot_adj_sel on public.purchase_lot_adjustments
  for select to authenticated
  using (exists (select 1 from public.purchase_lots l where l.id = lot_id and l.user_id = auth.uid()));
-- no insert/update/delete policies: the trail is written only by the RPCs.

-- Money columns move only inside the RPC handshake (same GUC card_sell uses).
create or replace function public.guard_purchase_lot()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  if (new.remaining_cost  is distinct from old.remaining_cost
      or new.remaining_count is distinct from old.remaining_count
      or new.total_cost   is distinct from old.total_cost
      or new.card_count   is distinct from old.card_count)
     and coalesce(auth.role(), '') = 'authenticated'
     and coalesce(current_setting('cardops.in_sell', true), '') <> '1' then
    raise exception 'lot balances move only through card_sell / card_unsell / speed_book_commit';
  end if;
  return new;
end $$;
drop trigger if exists purchase_lots_guard on public.purchase_lots;
create trigger purchase_lots_guard before update on public.purchase_lots
  for each row execute function public.guard_purchase_lot();

-- A card may only point at a lot owned by the SAME user (the FK alone would
-- accept another user's lot id, since FK checks bypass RLS).
create or replace function public.guard_card_lot_link()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  if new.purchase_lot_id is not null and not exists (
       select 1 from public.purchase_lots l
       where l.id = new.purchase_lot_id and l.user_id = new.user_id) then
    raise exception 'purchase lot belongs to a different user';
  end if;
  return new;
end $$;
drop trigger if exists cards_lot_link_guard on public.cards;
create trigger cards_lot_link_guard before insert or update of purchase_lot_id on public.cards
  for each row execute function public.guard_card_lot_link();

-- ── 2) card_sell: draw from the card's OWN purchase lot ─────────────────────
create or replace function public.card_sell(
  p_card_id uuid, p_platform text, p_sale_price numeric, p_fees numeric,
  p_ship_income numeric, p_ship_cost numeric, p_order_ref text)
returns jsonb language plpgsql security definer set search_path = public as $$
declare
  v_card public.cards%rowtype; v_lot public.purchase_lots%rowtype;
  v_basis numeric := 0; v_net numeric; v_pl numeric;
begin
  if not (public.owns_card(p_card_id) or auth.role() = 'service_role') then raise exception 'forbidden'; end if;

  select * into v_card from public.cards where id = p_card_id for update;
  if not found then raise exception 'card not found'; end if;
  if v_card.status = 'sold' then raise exception 'card already sold'; end if;
  if p_sale_price is null or p_sale_price < 0 then raise exception 'sale price required'; end if;

  v_net := coalesce(p_sale_price, 0) - coalesce(p_fees, 0) + coalesce(p_ship_income, 0) - coalesce(p_ship_cost, 0);

  perform set_config('cardops.in_sell', '1', true);

  if v_card.purchase_lot_id is not null then
    select * into v_lot from public.purchase_lots where id = v_card.purchase_lot_id for update;
    if found and v_lot.remaining_count > 0 then
      v_basis := round(v_lot.remaining_cost / v_lot.remaining_count, 2);
      insert into public.purchase_lot_adjustments
        (lot_id, kind, card_id, amount, remaining_cost_after, remaining_count_after, actor, note)
      values
        (v_lot.id, 'draw', p_card_id, -v_basis,
         v_lot.remaining_cost - v_basis, v_lot.remaining_count - 1,
         coalesce(auth.uid()::text, 'system'), 'Sale draw');
      update public.purchase_lots
        set remaining_cost = remaining_cost - v_basis, remaining_count = remaining_count - 1
        where id = v_lot.id;
    end if;
  else
    v_basis := coalesce(v_card.individual_basis, 0);
  end if;

  v_pl := v_net - v_basis;

  insert into public.card_sales
    (card_id, user_id, platform, sale_price, fees, shipping_income, shipping_cost, net_proceeds, basis_drawn, profit_loss, order_ref)
  values (p_card_id, v_card.user_id, p_platform, p_sale_price, p_fees, p_ship_income, p_ship_cost, v_net, v_basis, v_pl, p_order_ref);
  update public.cards set status = 'sold', sold_at = now(), basis_drawn = v_basis where id = p_card_id;

  return jsonb_build_object('net', v_net, 'basis', v_basis, 'profit_loss', v_pl);
end $$;

-- ── 3) card_unsell: reverse the lot draw this sale made ─────────────────────
create or replace function public.card_unsell(p_card_id uuid)
returns jsonb language plpgsql security definer set search_path = public as $$
declare
  v_card public.cards%rowtype; v_sale public.card_sales%rowtype;
  v_lot public.purchase_lots%rowtype; v_draw public.purchase_lot_adjustments%rowtype;
  v_restored numeric := 0; v_count int := 0;
begin
  if not (public.owns_card(p_card_id) or auth.role() = 'service_role') then
    raise exception 'forbidden';
  end if;

  select * into v_card from public.cards where id = p_card_id for update;
  if not found then raise exception 'card not found'; end if;
  if v_card.status <> 'sold' then raise exception 'card is not sold'; end if;

  -- Reverse the latest lot 'draw' for this card not already corrected. The
  -- adjustment trail is authoritative — not basis_drawn, not the current lot
  -- link — so the reversal is exact even for a $0 draw or a since-relinked card.
  select * into v_draw from public.purchase_lot_adjustments
    where card_id = p_card_id and kind = 'draw'
    order by ts desc, id desc limit 1;
  if v_draw.id is not null and not exists (
        select 1 from public.purchase_lot_adjustments
        where card_id = p_card_id and kind = 'correction'
          and (ts, id) > (v_draw.ts, v_draw.id)) then
    select * into v_lot from public.purchase_lots where id = v_draw.lot_id for update;
    if found then
      v_restored := -v_draw.amount;
      v_count := 1;
      perform set_config('cardops.in_sell', '1', true);
      insert into public.purchase_lot_adjustments
        (lot_id, kind, card_id, amount, remaining_cost_after, remaining_count_after, actor, note)
      values
        (v_lot.id, 'correction', p_card_id, v_restored,
         v_lot.remaining_cost + v_restored, v_lot.remaining_count + 1,
         coalesce(auth.uid()::text, 'system'), 'Sale reversed');
      update public.purchase_lots
        set remaining_cost = remaining_cost + v_restored, remaining_count = remaining_count + 1
        where id = v_lot.id;
    end if;
  end if;

  select * into v_sale from public.card_sales
    where card_id = p_card_id order by sold_at desc limit 1;
  if v_sale.id is not null then
    delete from public.card_sales where id = v_sale.id;
  end if;

  perform set_config('cardops.in_sell', '1', true);
  update public.cards
    set status = 'booked', sold_at = null, basis_drawn = null
    where id = p_card_id;

  return jsonb_build_object(
    'reversed_sale', v_sale.id,
    'restored_basis', v_restored,
    'restored_count', v_count
  );
end $$;

-- ── 4) speed_book_commit: a batch IS a purchase lot ─────────────────────────
create or replace function public.speed_book_commit(p_items jsonb, p_lot_cost numeric)
returns jsonb language plpgsql security definer set search_path = public as $$
declare
  v_lot_id uuid;
  v_item jsonb; v_cat text; v_year int := extract(year from now())::int;
  v_prefix text; v_seq int; v_sku text; v_id uuid; v_ids uuid[] := '{}'; v_n int := 0;
begin
  if not public.has_card_access() then raise exception 'forbidden'; end if;
  if p_lot_cost is null or p_lot_cost < 0 then raise exception 'lot cost required (0 allowed for a free lot)'; end if;
  if p_items is null or jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items) = 0 then raise exception 'no items'; end if;

  perform set_config('cardops.in_sell', '1', true);
  insert into public.purchase_lots
    (user_id, label, acquired_on, total_cost, card_count, remaining_cost, remaining_count)
  values
    (auth.uid(), 'Speed Book ' || to_char(now(), 'YYYY-MM-DD'), current_date,
     p_lot_cost, jsonb_array_length(p_items), p_lot_cost, jsonb_array_length(p_items))
  returning id into v_lot_id;

  for v_item in select value from jsonb_array_elements(p_items) loop
    v_cat := coalesce(nullif(v_item->>'cat', ''), 'OT');
    v_prefix := v_cat || '-' || v_year || '-';
    loop
      select coalesce(max(substring(sku from char_length(v_prefix) + 1)::int), 0) + 1 into v_seq
        from public.cards where sku like v_prefix || '%';
      v_sku := v_prefix || lpad(v_seq::text, 6, '0');
      begin
        insert into public.cards (sku, entity_id, sport_category, zone, quick_booked, purchase_lot_id, status)
        values (v_sku,
          case when public.is_owner() then 'bfa6ad79-0d3a-412b-a682-603aa9d23f1d'::uuid else null end,
          nullif(v_item->>'sport_category', ''), coalesce(nullif(v_item->>'zone', ''), 'BULK'),
          true, v_lot_id, 'booked')
        returning id into v_id;
        exit;
      exception when unique_violation then end;
    end loop;
    v_ids := array_append(v_ids, v_id); v_n := v_n + 1;
  end loop;

  return jsonb_build_object('inserted', v_n, 'ids', to_jsonb(v_ids), 'lot_id', v_lot_id, 'lot_cost', p_lot_cost);
end $$;

-- ── 5) fold any funded legacy pool, then drop the old world ─────────────────
do $$
declare r record; v_lot uuid;
begin
  for r in select * from public.card_pool
            where (total_cost > 0 or card_count > 0) and user_id is not null loop
    insert into public.purchase_lots
      (user_id, label, acquired_on, total_cost, card_count, remaining_cost, remaining_count)
    values (r.user_id, 'Legacy pool (pre-lot basis)', current_date,
            r.total_cost, r.card_count, r.total_cost, r.card_count)
    returning id into v_lot;
    update public.cards c set purchase_lot_id = v_lot
      where c.user_id = r.user_id and c.use_pool_basis = true
        and c.status <> 'sold' and c.purchase_lot_id is null;
  end loop;
end $$;

drop table if exists public.card_pool_adjustments;
drop table if exists public.card_pool;
alter table public.cards drop column if exists use_pool_basis;

-- ═══════════ 20260736000000_audit_log_actors.sql ═══════════
-- Audit integrity (foundation-fixes item 4b).
--
-- The actor CHECK allowed only ('web','mcp','cron','assistant'), but the eBay
-- sync writes actor 'ebay-sync' per settled order and the account-deletion
-- endpoint writes 'ebay' — both inserts were silently rejected (23514 inside
-- swallowed promises), so the ONLY per-order settlement trail and the
-- compliance proof-of-receipt log never existed. Widen the constraint to the
-- actors the code actually writes; the code side now goes through
-- auditOrThrow, so any future constraint/actor mismatch fails loudly instead.

do $$
declare c record;
begin
  for c in
    select conname from pg_constraint
     where conrelid = 'public.audit_log'::regclass
       and contype = 'c'
       and pg_get_constraintdef(oid) ilike '%actor%'
  loop
    execute format('alter table public.audit_log drop constraint %I', c.conname);
  end loop;
end $$;

alter table public.audit_log add constraint audit_log_actor_check
  check (actor in ('web','mcp','cron','assistant','ebay-sync','ebay'));

-- ═══════════ 20260737000000_credit_metering.sql ═══════════
-- ══════════════════════════════════════════════════════════════════════════
-- CREDIT METERING v2 + AI COST TELEMETRY (Beau, 2026-07-25)
--
-- The business model: users buy computation credits on the website and spend
-- them on metered AI work. Decisions locked with Beau:
--   · plan grants EXPIRE at period end (rollover capped at 1× allowance, 30d)
--   · purchased top-ups NEVER expire
--   · spending consumes the soonest-expiring bucket first (FIFO by expiry)
--   · retail price (credits, src/lib/cards/credits.ts COST table) is decoupled
--     from measured cost (ai_usage.cost_usd) — cache savings are margin
--   · SHADOW MODE now: everything records, nothing is refused. The
--     'credit_enforcement' service_config flag flips the app-side gate on.
--
-- What this migration does:
--   A. ai_usage — real token/cost telemetry per AI run (the measurement layer)
--   B. credit_ledger v2 — kind / expires_at / remaining / shortfall columns
--   C. credit_balance() v2, credit_grant(), credit_spend() (FIFO draw)
--   D. seeds the (off) enforcement flag
--
-- Ordering rule (prevention rule 7): the app charges AFTER the effect — the
-- estimate row lands first, then credit_spend records the draw. That is why
-- credit_spend never refuses: by the time it runs, the compute already
-- happened; refusing would hide a real cost. Refusal (when enforcement is on)
-- happens in app code BEFORE the AI call, via the same remaining-sum this
-- file's balance function uses.
-- ══════════════════════════════════════════════════════════════════════════

-- ── A. Usage telemetry — every metered vendor call, not just AI ────────────
--
-- ONE table, because users spend ONE currency. But vendor expenses have three
-- different COST SHAPES, and conflating them produces nonsense numbers:
--
--   'metered'      Anthropic tokens, Ximilar per-call. The dollar cost of a
--                  single call is known at call time -> cost_usd is real.
--   'subscription' PriceCharting, TheCardAPI. Flat monthly fee + quota: the
--                  marginal cost of one more call is $0 until the cap, then a
--                  step function. cost_usd is NULL by design — the true cost
--                  is the monthly fee ALLOCATED across the units actually
--                  consumed (see the usage_month_cost view below), which is a
--                  month-end number, not a call-time one.
--   'free'         Scryfall, eBay. No dollars; the scarce thing is quota.
--                  Metered anyway so a runaway loop is visible before it
--                  becomes a rate-limit outage.
--
-- So: ALWAYS record units; record dollars only where dollars are knowable.
-- cost_usd NULL therefore means "not directly attributable" — read alongside
-- cost_model, never silently treated as $0 (rule 9).
create table if not exists public.usage_events (
  id bigint generated always as identity primary key,
  user_id uuid not null,
  vendor text not null,                -- 'anthropic' | 'thecardapi' | 'pricecharting' | 'ximilar' | 'ebay' | 'scryfall'
  cost_model text not null default 'metered',
  feature text not null,               -- mirrors the ledger reason, e.g. 'estimate:standard_plus'
  model text,                          -- AI model id; null for non-AI vendors
  units integer not null default 1,    -- quota units consumed (1 = one call)
  input_tokens integer not null default 0,
  output_tokens integer not null default 0,
  cache_write_tokens integer not null default 0,
  cache_read_tokens integer not null default 0,
  cost_usd numeric(12, 6),             -- metered vendors only; null elsewhere BY DESIGN
  credits_charged integer not null default 0, -- 0 when the run wasn't billed (e.g. estimate not stored)
  ref uuid,                            -- card id / job id
  created_at timestamptz not null default now(),
  constraint usage_events_cost_model_chk check (cost_model in ('metered', 'subscription', 'free'))
);
create index if not exists usage_events_created_idx on public.usage_events (created_at desc);
create index if not exists usage_events_user_idx on public.usage_events (user_id, created_at desc);
create index if not exists usage_events_vendor_idx on public.usage_events (vendor, created_at desc);

-- Service-role writes only; the owner margin screen reads via the service
-- client. RLS on with no policies = closed to every non-service caller.
alter table public.usage_events enable row level security;

-- Month-end allocation: a subscription's fee spread across the units it
-- actually served that month. This is the ONLY honest per-call cost for a
-- fixed-fee vendor, and it falls as volume rises — which is the whole point
-- of watching it. Metered vendors report their real summed dollars instead.
create or replace view public.usage_month_cost as
select
  date_trunc('month', u.created_at) as month,
  u.vendor,
  u.cost_model,
  count(*)                          as calls,
  sum(u.units)                      as units,
  sum(u.credits_charged)            as credits_charged,
  sum(u.cost_usd)                   as direct_cost_usd,
  count(*) filter (where u.cost_usd is null and u.cost_model = 'metered') as unpriced_calls,
  case when u.cost_model = 'subscription'
    then (select sc.monthly_cost_est from public.service_config sc where sc.key = u.vendor)
  end                               as monthly_fee_usd,
  case when u.cost_model = 'subscription' and sum(u.units) > 0
    then (select sc.monthly_cost_est from public.service_config sc where sc.key = u.vendor) / sum(u.units)
  end                               as allocated_cost_per_unit
from public.usage_events u
group by 1, 2, 3;

-- ── B. credit_ledger v2 ────────────────────────────────────────────────────
alter table public.credit_ledger
  add column if not exists kind text not null default 'adjustment',
  add column if not exists expires_at timestamptz,
  add column if not exists remaining integer,
  add column if not exists shortfall integer not null default 0;

-- Backfill any pre-v2 rows (a freshly-bootstrapped DB has none): negatives
-- become spends; positives become grants funded at face value, then reduced
-- oldest-first by the total already spent — the same answer the old
-- sum(delta) balance gave.
do $$
declare v_user uuid; v_owe int; r record;
begin
  -- RE-ENTRY GUARD. Every other statement in this file is deliberately
  -- re-runnable (if not exists / or replace / on conflict) because migrations
  -- here are pasted by hand and files get re-pasted. This block is the one
  -- destructive statement: it re-applies each user's ENTIRE lifetime spend
  -- against their grant remainders, so a second run would silently debit
  -- already-reconciled spends again (1000-grant with 700 left and 300 spent
  -- becomes 400, then 100, then 0) with no error and no log. Bail out unless
  -- there is genuinely pre-v2 data to convert.
  if not exists (
    select 1 from public.credit_ledger
    where (delta < 0 and kind <> 'spend') or (delta > 0 and remaining is null)
  ) then
    return; -- already migrated (or an empty ledger) — nothing to backfill
  end if;

  update public.credit_ledger set kind = 'spend', remaining = null
    where delta < 0 and kind <> 'spend';
  update public.credit_ledger set remaining = delta
    where delta > 0 and remaining is null;
  for v_user in select distinct user_id from public.credit_ledger loop
    select coalesce(-sum(delta), 0) into v_owe
      from public.credit_ledger where user_id = v_user and kind = 'spend';
    for r in select id, remaining from public.credit_ledger
      where user_id = v_user and kind <> 'spend' and remaining > 0
      order by created_at, id
    loop
      exit when v_owe <= 0;
      update public.credit_ledger
        set remaining = greatest(0, remaining - v_owe) where id = r.id;
      v_owe := v_owe - r.remaining;
    end loop;
  end loop;
end $$;

alter table public.credit_ledger drop constraint if exists credit_ledger_kind_chk;
alter table public.credit_ledger add constraint credit_ledger_kind_chk
  check (kind in ('plan_grant', 'rollover', 'purchase', 'promo', 'adjustment', 'spend'));
alter table public.credit_ledger drop constraint if exists credit_ledger_shape_chk;
alter table public.credit_ledger add constraint credit_ledger_shape_chk check (
  (kind = 'spend' and delta < 0 and remaining is null)
  or (kind <> 'spend' and delta > 0 and remaining is not null
      and remaining >= 0 and remaining <= delta)
);
create index if not exists credit_ledger_draw_idx
  on public.credit_ledger (user_id, expires_at asc nulls last, id asc)
  where kind <> 'spend' and remaining > 0;

-- ── C. functions ───────────────────────────────────────────────────────────

-- Balance v2: what the signed-in user can actually spend — unexpired grant
-- remainders. (The old sum(delta) counted expired grants forever and let
-- spends push the number negative silently.)
create or replace function public.credit_balance()
returns integer language sql stable security definer set search_path = public as $$
  select coalesce(sum(remaining), 0)::int from public.credit_ledger
  where user_id = auth.uid() and kind <> 'spend'
    and (expires_at is null or expires_at > now());
$$;
revoke all on function public.credit_balance() from public;
grant execute on function public.credit_balance() to authenticated;

-- Grant credits. Service role (Stripe webhook, admin jobs) or the owner
-- (test grants from the credits screen). Positive grants only — spends go
-- through credit_spend so FIFO accounting can never be bypassed.
create or replace function public.credit_grant(
  p_user uuid, p_amount integer, p_kind text default 'adjustment',
  p_expires_at timestamptz default null, p_reason text default null
) returns jsonb language plpgsql security definer set search_path = public as $$
declare
  v_role text := coalesce(nullif(current_setting('request.jwt.claims', true), '')::jsonb ->> 'role', '');
  v_id bigint;
begin
  if v_role <> 'service_role' and not exists (
    select 1 from public.profiles where id = auth.uid() and role = 'owner'
  ) then
    raise exception 'credit_grant: only the owner or the service role may grant credits';
  end if;
  if p_amount is null or p_amount <= 0 then
    raise exception 'credit_grant: amount must be a positive integer';
  end if;
  if p_kind not in ('plan_grant', 'rollover', 'purchase', 'promo', 'adjustment') then
    raise exception 'credit_grant: invalid kind %', p_kind;
  end if;
  insert into public.credit_ledger (user_id, delta, kind, expires_at, remaining, reason)
    values (p_user, p_amount, p_kind, p_expires_at, p_amount, p_reason)
    returning id into v_id;
  return jsonb_build_object('id', v_id, 'granted', p_amount,
    'balance', (select coalesce(sum(remaining), 0) from public.credit_ledger
      where user_id = p_user and kind <> 'spend'
        and (expires_at is null or expires_at > now())));
end $$;
revoke all on function public.credit_grant(uuid, integer, text, timestamptz, text) from public;
grant execute on function public.credit_grant(uuid, integer, text, timestamptz, text) to authenticated, service_role;

-- Record a spend, drawing FIFO from the soonest-expiring unexpired grants.
-- Service role only (both app call sites run on the service client, after the
-- effect exists). NEVER refuses: if the buckets can't cover it, the uncovered
-- part lands in `shortfall` on the spend row — visible, not hidden. The
-- pre-flight refusal (enforcement mode) is app code, before the AI call.
create or replace function public.credit_spend(
  p_user uuid, p_amount integer, p_reason text, p_ref uuid default null
) returns jsonb language plpgsql security definer set search_path = public as $$
declare
  v_role text := coalesce(nullif(current_setting('request.jwt.claims', true), '')::jsonb ->> 'role', '');
  v_need integer; v_take integer; r record;
begin
  if v_role <> 'service_role' then
    raise exception 'credit_spend: service role only';
  end if;
  if p_amount is null or p_amount <= 0 then
    raise exception 'credit_spend: amount must be a positive integer';
  end if;
  v_need := p_amount;
  for r in select id, remaining from public.credit_ledger
    where user_id = p_user and kind <> 'spend' and remaining > 0
      and (expires_at is null or expires_at > now())
    order by expires_at asc nulls last, id asc
    for update
  loop
    exit when v_need = 0;
    v_take := least(r.remaining, v_need);
    update public.credit_ledger set remaining = remaining - v_take where id = r.id;
    v_need := v_need - v_take;
  end loop;
  insert into public.credit_ledger (user_id, delta, kind, reason, ref, shortfall)
    values (p_user, -p_amount, 'spend', p_reason, p_ref, v_need);
  return jsonb_build_object('spent', p_amount, 'covered', p_amount - v_need,
    'shortfall', v_need,
    'balance', (select coalesce(sum(remaining), 0) from public.credit_ledger
      where user_id = p_user and kind <> 'spend'
        and (expires_at is null or expires_at > now())));
end $$;
revoke all on function public.credit_spend(uuid, integer, text, uuid) from public;
grant execute on function public.credit_spend(uuid, integer, text, uuid) to service_role;

-- ── D. enforcement flag — OFF (shadow mode) until billing exists ───────────
insert into public.service_config (key, enabled, notes)
values ('credit_enforcement', false,
  'ON = estimate runs are refused when the credit balance cannot cover them. OFF = shadow mode: spends record (with shortfall) but nothing is blocked.')
on conflict (key) do nothing;

-- ═══════════ 20260738000000_card_identities.sql ═══════════
-- ══════════════════════════════════════════════════════════════════════════
-- CARD IDENTITY LAYER (Beau, 2026-07-25) — the foundation for multiple users.
--
-- THE PROBLEM. Market data was keyed to a USER'S CARD ROW:
--   card_market_sales.card_id -> cards(id) on delete cascade
-- so twenty people owning the same 2020 Prizm Herbert PSA 10 meant twenty
-- separate fetches, twenty copies, twenty vendor charges — and each copy
-- started EMPTY the day that user added the card. Deleting the card destroyed
-- the history. Liquidity needs 90-365 days of sales while the vendor's free
-- tier only looks back 3 days, so a new user's collection reads "too thin to
-- say" for months. That is a cold start we would ship to every customer.
--
-- THE FIX. A canonical PRINT IDENTITY — one row per real-world card, shared
-- across every tenant — with market sales attached to the identity instead of
-- to somebody's copy of it. Consequences, all good:
--   · vendor spend falls as ownership overlaps (the whole point at scale)
--   · a new user inherits every day of history we have ever collected
--   · liquidity works on day one instead of month six
--   · deleting a card no longer destroys shared market data
--
-- SCOPE NOTE. Identity is the card AS PRINTED (set/year/player/number/
-- parallel). Grader and grade are properties of a COPY and of each observed
-- sale, not of the identity — sales carry their own grader/grade and the
-- pricing code already filters them to match the card's condition. Do not add
-- grade to the fingerprint: it would re-fragment exactly what this unifies.
-- ══════════════════════════════════════════════════════════════════════════

-- ── Deterministic normalization ────────────────────────────────────────────
-- ONE implementation, in SQL, called from a trigger — never mirrored in TS.
-- Two implementations of a fingerprint drift, and a drifted fingerprint
-- silently splits one identity into two (re-creating the cold start it exists
-- to prevent). '~' marks an absent part so positions can't shift.
create or replace function public.norm_token(p text)
returns text language sql immutable as $$
  select coalesce(nullif(regexp_replace(lower(trim(coalesce(p, ''))), '[^a-z0-9]+', '', 'g'), ''), '~');
$$;

create or replace function public.card_fingerprint(
  p_sport text, p_year int, p_set text, p_player text, p_number text, p_parallel text
) returns text language sql immutable as $$
  select public.norm_token(p_sport) || '|' ||
         coalesce(p_year::text, '~')  || '|' ||
         public.norm_token(p_set)     || '|' ||
         public.norm_token(p_player)  || '|' ||
         public.norm_token(p_number)  || '|' ||
         public.norm_token(p_parallel);
$$;

-- ── The shared catalog ─────────────────────────────────────────────────────
create table if not exists public.card_identities (
  id uuid primary key default gen_random_uuid(),
  fingerprint text not null unique,
  sport_category text,
  year int,
  set_name text,
  player text,
  card_number text,
  parallel text,
  -- When the market feed last pulled for this identity. Lets the refresh job
  -- rotate over IDENTITIES (fetch once, serve every owner) instead of over
  -- cards (fetch once per owner for the same data).
  last_refreshed_at timestamptz,
  created_at timestamptz not null default now()
);
create index if not exists card_identities_refresh_idx
  on public.card_identities (last_refreshed_at asc nulls first);
create index if not exists card_identities_player_idx on public.card_identities (player);

-- Catalog facts are not tenant data: any card user reads them. Nobody writes
-- directly — writes go through resolve_card_identity below, so one tenant can
-- never corrupt or enumerate-poison the shared table.
alter table public.card_identities enable row level security;
do $$ begin
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='card_identities' and policyname='card_identities_read') then
    create policy card_identities_read on public.card_identities
      for select to authenticated using (public.has_card_access());
  end if;
end $$;

-- ── Resolve (upsert-and-return) ────────────────────────────────────────────
create or replace function public.resolve_card_identity(
  p_sport text, p_year int, p_set text, p_player text, p_number text, p_parallel text
) returns uuid language plpgsql security definer set search_path = public as $$
declare v_fp text; v_id uuid;
begin
  -- SECURITY DEFINER writing to a CROSS-TENANT table: gate it. Without this,
  -- any authenticated account — including one with no card access at all —
  -- could write unlimited rows into the shared catalog every other tenant
  -- reads. The definer bypasses RLS, so the check has to live here.
  if not public.has_card_access() and coalesce(auth.role(), '') <> 'service_role' then
    raise exception 'resolve_card_identity: card access required';
  end if;
  -- Too little to identify anything: no player AND no set means this would be
  -- a junk identity that every under-filled card in the system collides into.
  if public.norm_token(p_player) = '~' and public.norm_token(p_set) = '~' then
    return null;
  end if;
  v_fp := public.card_fingerprint(p_sport, p_year, p_set, p_player, p_number, p_parallel);
  select id into v_id from public.card_identities where fingerprint = v_fp;
  if v_id is not null then return v_id; end if;
  -- on conflict handles the race between two users adding the same card at once
  insert into public.card_identities
    (fingerprint, sport_category, year, set_name, player, card_number, parallel)
  values (v_fp, p_sport, p_year, p_set, p_player, p_number, p_parallel)
  on conflict (fingerprint) do update set fingerprint = excluded.fingerprint
  returning id into v_id;
  return v_id;
end $$;
revoke all on function public.resolve_card_identity(text, int, text, text, text, text) from public;
grant execute on function public.resolve_card_identity(text, int, text, text, text, text) to authenticated, service_role;

-- ── Cards point at their identity, maintained by TRIGGER ───────────────────
-- A trigger, not app code: intake, CSV import, Speed Book, the manual form and
-- anything added later all get an identity without remembering to ask for one.
-- One place to be right.
alter table public.cards add column if not exists identity_id uuid references public.card_identities(id);
create index if not exists cards_identity_idx on public.cards (identity_id);

create or replace function public.cards_set_identity()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  new.identity_id := public.resolve_card_identity(
    new.sport_category, new.year, new.set_name, new.player, new.card_number, new.parallel);
  return new;
end $$;

drop trigger if exists cards_identity_biu on public.cards;
create trigger cards_identity_biu
  before insert or update of sport_category, year, set_name, player, card_number, parallel
  on public.cards for each row execute function public.cards_set_identity();

-- Backfill (no-op on a fresh install). Updating identity_id does not re-fire
-- the trigger above, which watches only the identifying columns.
update public.cards
   set identity_id = public.resolve_card_identity(sport_category, year, set_name, player, card_number, parallel)
 where identity_id is null;

-- ── Market sales move to the identity ──────────────────────────────────────
alter table public.card_market_sales
  add column if not exists identity_id uuid references public.card_identities(id) on delete cascade;

update public.card_market_sales m
   set identity_id = c.identity_id
  from public.cards c
 where m.card_id = c.id and m.identity_id is null;

-- Dedup by identity now.
--
-- NOT a partial index. It was `where identity_id is not null`, which looked
-- tidier and silently broke the entire layer: Postgres only infers a PARTIAL
-- unique index as an ON CONFLICT arbiter when the statement repeats the index
-- predicate, and PostgREST's `on_conflict=` can only emit a bare column list.
-- Every upsert from the refresh cron would have failed with 42P10 — and that
-- error was swallowed — so card_market_sales would never have gained a row
-- while the run reported success. NULL identity_ids are distinct in a plain
-- unique index anyway, so the predicate bought nothing.
drop index if exists public.card_market_sales_dedup;
create unique index if not exists card_market_sales_identity_dedup
  on public.card_market_sales (identity_id, source, external_id);
create index if not exists card_market_sales_identity_sold_idx
  on public.card_market_sales (identity_id, sold_at desc);

-- ── RLS: the sales are SHARED market facts, not tenant data ───────────────
-- 20260724 (multi-tenant) had replaced the original shared policy with
-- `owns_card(card_id)`. Left alone, that would have defeated this entire
-- migration: rows are written with the group representative's card_id, so
-- every OTHER owner of the same identity would read an empty history — and
-- once card_id goes NULL on delete, owns_card(null) is false and the row
-- becomes invisible to everyone, forever.
--
-- Reads: any card user (these are public marketplace observations, keyed to a
-- catalog identity — the same posture as card_identities above).
-- Writes: SERVICE ROLE ONLY. A tenant-writable shared table would let anyone
-- inject fabricated sales into an identity that prices everyone else's copies.
do $$ begin
  if exists (select 1 from pg_policies where schemaname='public' and tablename='card_market_sales' and policyname='card_market_sales_own') then
    drop policy card_market_sales_own on public.card_market_sales;
  end if;
  if exists (select 1 from pg_policies where schemaname='public' and tablename='card_market_sales' and policyname='card_market_sales_all') then
    drop policy card_market_sales_all on public.card_market_sales;
  end if;
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='card_market_sales' and policyname='card_market_sales_read') then
    create policy card_market_sales_read on public.card_market_sales
      for select to authenticated using (public.has_card_access());
  end if;
end $$;
-- No INSERT/UPDATE/DELETE policy: authenticated callers cannot write. The
-- price-refresh cron writes with the service client, which bypasses RLS.

-- card_id survives as provenance (which copy first caused us to fetch this),
-- but MUST NOT cascade: deleting one user's card can no longer delete market
-- history that every other owner of that card depends on.
alter table public.card_market_sales alter column card_id drop not null;
alter table public.card_market_sales drop constraint if exists card_market_sales_card_id_fkey;
alter table public.card_market_sales
  add constraint card_market_sales_card_id_fkey
  foreign key (card_id) references public.cards(id) on delete set null;

-- ═══════════ 20260739000000_investor_assets.sql ═══════════
-- ══════════════════════════════════════════════════════════════════════════
-- WAVE B — THE INVESTOR-ASSET RECORD (Beau, 2026-07-25)
-- Design: reference/DESIGN_WAVE_B.md. Schema half; UI follows.
--
-- The app models a card as dealer inventory moving through a sales funnel.
-- An investor asset is the opposite: it may never be listed, and its value
-- lives in DOCUMENTATION. The questions are "can I prove my basis", "can I
-- prove the chain of custody", "where is it and when is it coming back".
--
-- Three tables, deliberately separate from `cards` (sparse rows, and `cards`
-- is already wide and hit by every list query), plus the tax-bucket
-- inheritance chain and two guarded transitions.
-- ══════════════════════════════════════════════════════════════════════════

-- ── A. Documents — the thing the value actually lives in ───────────────────
-- `proves` is the load-bearing column: it turns a folder of PDFs into an
-- evidence packet, and lets the app say "your basis has no supporting
-- document" instead of showing an undefended number.
create table if not exists public.card_documents (
  id uuid primary key default gen_random_uuid(),
  card_id uuid not null references public.cards(id) on delete restrict,
  user_id uuid not null default auth.uid(),
  proves text not null check (proves in
    ('basis','reported_value','grade','insured_value','custody','title','provenance','other')),
  kind text,                         -- 'appraisal','form_706','cert','receipt','policy'
  bucket text not null default 'receipts',
  path text not null,
  doc_date date,
  bytes bigint,
  -- Integrity: evidence that can't be shown unaltered is weaker evidence, and
  -- this is what makes the backup VERIFIABLE rather than merely present.
  sha256 text,
  backup_state text not null default 'pending'
    check (backup_state in ('pending','backed_up','failed')),
  backup_error text,
  backed_up_at timestamptz,
  created_at timestamptz not null default now()
);
create index if not exists card_documents_card_idx on public.card_documents (card_id, created_at desc);
create index if not exists card_documents_backup_idx on public.card_documents (backup_state, created_at)
  where backup_state <> 'backed_up';

alter table public.card_documents enable row level security;
do $$ begin
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='card_documents' and policyname='card_documents_own') then
    create policy card_documents_own on public.card_documents for all to authenticated
      using (public.owns_card(card_id)) with check (public.owns_card(card_id));
  end if;
end $$;

-- ── B. The asset record (1:1 with an investor-bucket card) ─────────────────
create table if not exists public.card_asset_records (
  card_id uuid primary key references public.cards(id) on delete restrict,
  user_id uuid not null default auth.uid(),
  -- provenance: the PARTY, distinct from cards.acquisition_source (the channel)
  acquired_from text,
  acquired_relation text,
  -- basis provenance. The enum is not decoration: §1014 (step-up) vs §1015
  -- (carryover) is the difference between a stepped-up and an inherited-cost
  -- basis, and each carries a different substantiation requirement.
  basis_amount numeric(14,2),
  basis_source text check (basis_source in
    ('purchase_receipt','1014_step_up','1015_carryover','1022_modified','other')),
  basis_doc_id uuid references public.card_documents(id) on delete set null,
  appraisal_author text,
  appraisal_credential text,
  appraisal_date date,
  estate_reported_value numeric(14,2),
  -- The most commonly missed rule in stepped-up basis; surfaced as a warning.
  reported_value_caps_basis boolean not null default false,
  -- grade verification
  grade_verification text check (grade_verification in
    ('verified','unverified_grader','pending_crossover','crossover_failed')),
  crossover_target_grader text,
  crossover_min_grade numeric(4,1),
  -- insurance. Deliberately its own number: insured value, basis and market
  -- value are three different things and must never be conflated.
  insured_value numeric(14,2),
  insurer text,
  policy_ref text,
  insurance_valued_at date,
  -- legal title, separate from physical custody
  legal_title_holder text check (legal_title_holder in
    ('individual','trust','estate','joint','entity')),
  legal_title_detail text,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
alter table public.card_asset_records enable row level security;
do $$ begin
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='card_asset_records' and policyname='card_asset_records_own') then
    create policy card_asset_records_own on public.card_asset_records for all to authenticated
      using (public.owns_card(card_id)) with check (public.owns_card(card_id));
  end if;
end $$;

-- ── C. Chain of custody — APPEND ONLY ──────────────────────────────────────
-- A chain of custody you can edit is not a chain of custody. Same discipline
-- as purchase_lot_adjustments: insert and select only.
create table if not exists public.card_custody_log (
  id bigint generated always as identity primary key,
  card_id uuid not null references public.cards(id) on delete restrict,
  user_id uuid not null default auth.uid(),
  from_state text,
  to_state text not null,
  counterparty text,
  location text,
  sent_at timestamptz not null default now(),
  expected_back date,
  -- Stamped on the row that CLOSES a move (the return to possession). It is
  -- NOT used to find open moves: because the log is append-only, an earlier
  -- row is never edited to mark it closed. Current truth lives on
  -- `cards.asset_state`; this log is the history behind it.
  returned_at timestamptz,
  tracking_ref text,
  declared_value numeric(14,2),
  document_id uuid references public.card_documents(id) on delete set null,
  note text,
  created_at timestamptz not null default now()
);
create index if not exists card_custody_card_idx on public.card_custody_log (card_id, created_at desc);

alter table public.card_custody_log enable row level security;
do $$ begin
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='card_custody_log' and policyname='card_custody_log_read') then
    create policy card_custody_log_read on public.card_custody_log for select to authenticated
      using (public.owns_card(card_id));
  end if;
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='card_custody_log' and policyname='card_custody_log_insert') then
    create policy card_custody_log_insert on public.card_custody_log for insert to authenticated
      with check (public.owns_card(card_id));
  end if;
end $$;
-- No UPDATE or DELETE policy exists, so RLS refuses both for authenticated
-- callers. Belt and braces for anything running as a definer:
create or replace function public.guard_custody_append_only()
returns trigger language plpgsql as $$
begin
  raise exception 'card_custody_log is append-only: correct by adding a row, never by editing one';
end $$;
drop trigger if exists custody_append_only on public.card_custody_log;
create trigger custody_append_only before update or delete on public.card_custody_log
  for each row execute function public.guard_custody_append_only();

-- ── D. Cards: the tax-bucket inheritance chain + asset state ───────────────
-- ONE authoritative value with a documented lineage, never two sources of
-- truth. The LOT carries the default (a purchase usually has one intent); the
-- CARD carries the resolved value, because the tax test is per-property and
-- the Schedule D line is per-card — and one lot legitimately holds two intents
-- (buy 500 to flip 490, keep 10).
alter table public.cards
  add column if not exists tax_bucket text
    check (tax_bucket in ('investment','dealer','hobby')),
  add column if not exists tax_bucket_source text
    check (tax_bucket_source in ('lot_default','explicit_override')),
  add column if not exists tax_bucket_set_at timestamptz,
  add column if not exists tax_bucket_reason text,
  -- Orthogonal to `status`. A vaulted asset is not 'hold' — it has a funnel
  -- position AND a physical disposition, and collapsing them loses one.
  add column if not exists asset_state text
    check (asset_state in ('in_my_possession','at_appraisal','out_for_crossover',
                           'at_auction_house_on_consignment','vaulted',
                           'pledged_as_collateral','crossover_failed'));
create index if not exists cards_asset_state_idx on public.cards (asset_state)
  where asset_state is not null;
create index if not exists cards_tax_bucket_idx on public.cards (user_id, tax_bucket);

-- Inherit the lot's bucket at creation. Same trigger philosophy as identity:
-- one place, so no intake path can forget.
create or replace function public.cards_inherit_tax_bucket()
returns trigger language plpgsql security definer set search_path = public as $$
declare v_bucket text;
begin
  if new.tax_bucket is null and new.purchase_lot_id is not null then
    select tax_bucket into v_bucket from public.purchase_lots where id = new.purchase_lot_id;
    if v_bucket is not null then
      new.tax_bucket := v_bucket;
      new.tax_bucket_source := 'lot_default';
      new.tax_bucket_set_at := now();
      new.tax_bucket_reason := 'inherited from purchase lot';
    end if;
  end if;
  return new;
end $$;
drop trigger if exists cards_tax_bucket_bi on public.cards;
create trigger cards_tax_bucket_bi before insert on public.cards
  for each row execute function public.cards_inherit_tax_bucket();

-- Reclass is an explicit ACTION, not an edit. A tax classification that can be
-- silently changed is not defensible; this forces a reason and an audit row.
-- Guards the WHOLE provenance record, not just the value. Watching only
-- `tax_bucket` left the three columns that make it defensible — source, when,
-- and why — freely editable, so a classification could keep its audit trail
-- while the trail was quietly rewritten to say something else.
create or replace function public.guard_tax_bucket()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  if (new.tax_bucket is distinct from old.tax_bucket
      or new.tax_bucket_source is distinct from old.tax_bucket_source
      or new.tax_bucket_set_at is distinct from old.tax_bucket_set_at
      or new.tax_bucket_reason is distinct from old.tax_bucket_reason)
     and coalesce(auth.role(), '') = 'authenticated'
     and coalesce(current_setting('cardops.in_reclass', true), '') <> '1' then
    raise exception 'tax_bucket is a classification, not a field: use card_reclass_tax_bucket';
  end if;
  return new;
end $$;

-- asset_state had NO guard at all, which made the pledged-collateral block
-- bypassable in two calls: set asset_state to something else, then sell. It
-- also let the card's state drift away from the custody log that is supposed
-- to be its history. Both now require going through card_move_asset.
create or replace function public.guard_asset_state()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  if new.asset_state is distinct from old.asset_state
     and coalesce(auth.role(), '') = 'authenticated'
     and coalesce(current_setting('cardops.in_move', true), '') <> '1' then
    raise exception 'asset_state is a custody transition: use card_move_asset';
  end if;
  return new;
end $$;
drop trigger if exists cards_asset_state_guard on public.cards;
create trigger cards_asset_state_guard before update on public.cards
  for each row execute function public.guard_asset_state();
drop trigger if exists cards_tax_bucket_guard on public.cards;
create trigger cards_tax_bucket_guard before update on public.cards
  for each row execute function public.guard_tax_bucket();

create or replace function public.card_reclass_tax_bucket(
  p_card uuid, p_bucket text, p_reason text
) returns jsonb language plpgsql security definer set search_path = public as $$
declare v_old text; v_uid uuid := auth.uid();
begin
  if p_bucket not in ('investment','dealer','hobby') then
    raise exception 'card_reclass_tax_bucket: bucket must be investment, dealer or hobby';
  end if;
  -- The reason is the point: it is what makes the classification defensible
  -- later, and the app records YOUR determination, it does not make one.
  if coalesce(btrim(p_reason), '') = '' then
    raise exception 'card_reclass_tax_bucket: a reason is required';
  end if;
  select tax_bucket into v_old from public.cards where id = p_card and user_id = v_uid;
  if not found then raise exception 'card_reclass_tax_bucket: card not found'; end if;

  perform set_config('cardops.in_reclass', '1', true);
  update public.cards
     set tax_bucket = p_bucket, tax_bucket_source = 'explicit_override',
         tax_bucket_set_at = now(), tax_bucket_reason = p_reason
   where id = p_card and user_id = v_uid;
  perform set_config('cardops.in_reclass', '', true);

  insert into public.audit_log (actor, action, target, payload, result)
  values ('web', 'card.tax_bucket.reclass', p_card::text,
          jsonb_build_object('from', v_old, 'to', p_bucket, 'reason', p_reason, 'user_id', v_uid),
          'ok');
  return jsonb_build_object('card_id', p_card, 'from', v_old, 'to', p_bucket);
end $$;
revoke all on function public.card_reclass_tax_bucket(uuid, text, text) from public;
grant execute on function public.card_reclass_tax_bucket(uuid, text, text) to authenticated;

-- ── E. Custody moves — the state machine ───────────────────────────────────
-- Every transition writes a log row; that log IS the chain of custody. Every
-- state except in_my_possession and vaulted requires an expected return date,
-- because a consignment with no return date is itself a finding.
create or replace function public.card_move_asset(
  p_card uuid, p_to_state text, p_counterparty text default null,
  p_location text default null, p_expected_back date default null,
  p_tracking text default null, p_declared_value numeric default null,
  p_note text default null, p_document uuid default null
) returns jsonb language plpgsql security definer set search_path = public as $$
declare v_from text; v_uid uuid := auth.uid();
begin
  if p_to_state not in ('in_my_possession','at_appraisal','out_for_crossover',
                        'at_auction_house_on_consignment','vaulted',
                        'pledged_as_collateral','crossover_failed') then
    raise exception 'card_move_asset: unknown state %', p_to_state;
  end if;
  select asset_state into v_from from public.cards where id = p_card and user_id = v_uid;
  if not found then raise exception 'card_move_asset: card not found'; end if;
  if p_to_state not in ('in_my_possession','vaulted') and p_expected_back is null then
    raise exception 'card_move_asset: % requires an expected return date', p_to_state;
  end if;

  perform set_config('cardops.in_move', '1', true);
  update public.cards set asset_state = p_to_state where id = p_card and user_id = v_uid;
  perform set_config('cardops.in_move', '', true);

  insert into public.card_custody_log
    (card_id, user_id, from_state, to_state, counterparty, location, expected_back,
     tracking_ref, declared_value, document_id, note,
     returned_at)
  values (p_card, v_uid, v_from, p_to_state, p_counterparty, p_location, p_expected_back,
          p_tracking, p_declared_value, p_document, p_note,
          case when p_to_state = 'in_my_possession' then now() end);

  return jsonb_build_object('card_id', p_card, 'from', v_from, 'to', p_to_state);
end $$;
revoke all on function public.card_move_asset(uuid, text, text, text, date, text, numeric, text, uuid) from public;
grant execute on function public.card_move_asset(uuid, text, text, text, date, text, numeric, text, uuid) to authenticated;

-- The aging board: assets out of your hands, with the expected-return date
-- from the move that put them there. Derived from the CARD's current state
-- (truth) joined to its latest custody row (context) — never from a mutable
-- flag on the log.
-- security_invoker: a view runs as its OWNER by default, which would bypass
-- every RLS policy underneath it and hand each authenticated user a list of
-- EVERY tenant's out-of-possession assets — counterparty, location, declared
-- value. The whole aging board is a leak without this one setting.
create or replace view public.card_assets_out
with (security_invoker = true) as
select c.id as card_id, c.user_id, c.player, c.year, c.set_name, c.asset_state,
       l.counterparty, l.location, l.sent_at, l.expected_back, l.declared_value,
       case
         when l.expected_back is null then 'no_due_date'
         when l.expected_back < current_date then 'overdue'
         else 'ok'
       end as aging
from public.cards c
join lateral (
  select * from public.card_custody_log cl
  where cl.card_id = c.id order by cl.created_at desc, cl.id desc limit 1
) l on true
where c.asset_state is not null
  and c.asset_state not in ('in_my_possession','vaulted');

-- ── F. Pledged property cannot be sold ─────────────────────────────────────
-- Enforced in the database, not hidden in the UI — selling property pledged as
-- collateral is the kind of mistake that ends relationships.
create or replace function public.guard_pledged_not_sold()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  if new.status is distinct from old.status and new.status in ('sold','listed')
     and old.asset_state = 'pledged_as_collateral' then
    raise exception 'this asset is pledged as collateral — release it before listing or selling';
  end if;
  return new;
end $$;
drop trigger if exists cards_pledged_guard on public.cards;
create trigger cards_pledged_guard before update on public.cards
  for each row execute function public.guard_pledged_not_sold();

-- ═══════════ 20260740000000_photo_provenance_storage.sql ═══════════
-- ══════════════════════════════════════════════════════════════════════════
-- PHOTO PROVENANCE + STORAGE METERING (Beau, 2026-07-25)
-- Design: reference/DESIGN_PHOTO_SYSTEM.md §4 (crop integrity) and §6 (storage).
--
-- Two jobs, both of which get much harder the longer they wait:
--
-- 1. PROVENANCE. The camera now keeps the full uncropped frame beside the
--    margin crop. Until this migration there was nowhere to say which is
--    which, and — worse — the CROPPED image was being stored as
--    variant='original', so the labels actively lied. Corners and edges are
--    the grade; the record of which pixels were removed has to be part of the
--    row, not folklore.
--
-- 2. MEASUREMENT. Storage is the second meter beside credits, and unlike AI
--    spend it recurs every month forever whether or not the user ever returns.
--    You cannot bill, cap, or even warn on bytes you never recorded, and the
--    history is unrecoverable if measurement starts late — so `bytes` lands
--    now, long before any quota exists to enforce.
-- ══════════════════════════════════════════════════════════════════════════

-- ── A. card_photos: provenance + size ──────────────────────────────────────
alter table public.card_photos
  -- Which shot in a template this is. Wider than the old front/back/slab/defect
  -- so corner and surface shots (the grading template) have somewhere to live.
  add column if not exists role text,
  -- Points at the uncropped frame this was derived from. Null on originals.
  add column if not exists derived_from uuid references public.card_photos(id) on delete set null,
  -- {quad, margin_pct, deskewed} — how the derivative was produced, so any
  -- crop can be audited against its source rather than trusted.
  add column if not exists crop_geometry jsonb,
  add column if not exists width int,
  add column if not exists height int,
  -- REQUIRED for metering. Nullable only so pre-existing rows don't block the
  -- migration; new writes always set it.
  add column if not exists bytes bigint,
  add column if not exists capture_meta jsonb;

create index if not exists card_photos_derived_idx on public.card_photos (derived_from)
  where derived_from is not null;

-- The old CHECK only allowed front/back/slab/defect. Template shots need more.
alter table public.card_photos drop constraint if exists card_photos_kind_check;
alter table public.card_photos add constraint card_photos_kind_check check (kind in
  ('front','back','slab','defect',
   'corner_tl','corner_tr','corner_bl','corner_br',
   'corner_tl_back','corner_tr_back','corner_bl_back','corner_br_back',
   'surface_angle','edge','other'));

-- ── B. Per-user storage rollup ─────────────────────────────────────────────
-- Maintained on write. NOT computed by scanning the bucket: a number you have
-- to go and calculate is a number nobody looks at, and the whole point is to
-- warn a user BEFORE they hit a wall rather than explain it afterwards.
create table if not exists public.user_storage_usage (
  user_id uuid primary key,
  bytes bigint not null default 0,
  objects int not null default 0,
  updated_at timestamptz not null default now()
);
alter table public.user_storage_usage enable row level security;
do $$ begin
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='user_storage_usage' and policyname='user_storage_usage_self') then
    create policy user_storage_usage_self on public.user_storage_usage for select to authenticated
      using (user_id = auth.uid());
  end if;
end $$;

-- The owner is DENORMALISED onto the photo row, and that is load-bearing.
--
-- Resolving it with `select user_id from cards where id = old.card_id` looked
-- equivalent and was not: card_photos cascade-deletes with its card, so by the
-- time the delete trigger ran the card was already gone, the lookup returned
-- null, and the function bailed before decrementing. Deleting a card silently
-- kept charging the user for its photos forever — and a quota built on that
-- number would have been unfixable after the fact.
alter table public.card_photos add column if not exists user_id uuid;
update public.card_photos p set user_id = c.user_id
  from public.cards c where c.id = p.card_id and p.user_id is null;

create or replace function public.card_photos_set_owner()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  if new.user_id is null then
    select user_id into new.user_id from public.cards where id = new.card_id;
  end if;
  return new;
end $$;
drop trigger if exists card_photos_owner_bi on public.card_photos;
create trigger card_photos_owner_bi before insert on public.card_photos
  for each row execute function public.card_photos_set_owner();

create or replace function public.bump_storage_usage()
returns trigger language plpgsql security definer set search_path = public as $$
declare v_user uuid; v_bytes bigint; v_objects int;
begin
  if tg_op = 'INSERT' then
    v_user := new.user_id;
    v_bytes := coalesce(new.bytes, 0); v_objects := 1;
  elsif tg_op = 'DELETE' then
    v_user := old.user_id;   -- survives the parent card's deletion
    v_bytes := -coalesce(old.bytes, 0); v_objects := -1;
  else
    -- UPDATE: only a size change matters.
    v_user := coalesce(new.user_id, old.user_id);
    v_bytes := coalesce(new.bytes, 0) - coalesce(old.bytes, 0); v_objects := 0;
  end if;
  if v_user is null then return coalesce(new, old); end if;

  insert into public.user_storage_usage (user_id, bytes, objects, updated_at)
  values (v_user, greatest(0, v_bytes), greatest(0, v_objects), now())
  on conflict (user_id) do update
    set bytes = greatest(0, public.user_storage_usage.bytes + v_bytes),
        objects = greatest(0, public.user_storage_usage.objects + v_objects),
        updated_at = now();
  return coalesce(new, old);
end $$;

drop trigger if exists card_photos_storage_ai on public.card_photos;
create trigger card_photos_storage_ai after insert or update of bytes or delete
  on public.card_photos for each row execute function public.bump_storage_usage();

-- Backfill the rollup from whatever is already recorded (no-op on a fresh DB;
-- pre-existing rows have null bytes and simply count as objects).
insert into public.user_storage_usage (user_id, bytes, objects, updated_at)
select c.user_id, coalesce(sum(p.bytes), 0), count(*), now()
from public.card_photos p join public.cards c on c.id = p.card_id
group by c.user_id
on conflict (user_id) do update
  set bytes = excluded.bytes, objects = excluded.objects, updated_at = now();

-- ═══════════ 20260741000000_photo_prefs.sql ═══════════
-- ══════════════════════════════════════════════════════════════════════════
-- PHOTO CAPTURE PREFERENCES (Beau, 2026-07-25) — CAPTURE_WORK_ITEMS.md P2.
--
-- "All of these things should have variations in settings people can save
-- along with what they set as defaults."
--
-- Extends card_user_prefs rather than adding a card_photo_prefs table: it is
-- the same concern (one row per user, own-row RLS, one upsert path), and a
-- second table would mean a second policy and a second API route to keep in
-- step for no gain.
--
-- Every knob here changes how many BYTES a card costs to keep, which is why
-- the quality preset and keep_originals sit next to each other: storage is a
-- metered resource (20260740) and the trade has to be visible where the choice
-- is made, not discovered on a bill.
-- ══════════════════════════════════════════════════════════════════════════

alter table public.card_user_prefs
  -- 'in_app' = the scanner with guide + auto-snap; 'os_camera' = hand off to
  -- the phone's own camera app. The fallback stays selectable because the OS
  -- camera applies HDR and noise reduction we cannot reproduce on a raw frame.
  add column if not exists capture_mode text not null default 'in_app'
    check (capture_mode in ('in_app', 'os_camera')),
  add column if not exists photo_quality text not null default 'standard'
    check (photo_quality in ('economy', 'standard', 'high', 'archive')),
  add column if not exists auto_snap boolean not null default false,
  add column if not exists burst_count int not null default 3
    check (burst_count between 1 and 5),
  add column if not exists auto_crop text not null default 'margin'
    check (auto_crop in ('off', 'margin', 'tight')),
  -- Percent of card width kept as background around the crop. Bounded, not
  -- free: 0 puts the card's edge ON the image boundary, which is exactly the
  -- misrepresentation the margin exists to prevent.
  add column if not exists crop_margin_pct numeric(4,3) not null default 0.040
    check (crop_margin_pct between 0.005 and 0.250),
  add column if not exists keep_originals boolean not null default true,
  add column if not exists default_template text;

-- Named bundles: "bulk intake" vs "consignment quality", so switching working
-- modes is one tap instead of re-tuning six knobs.
create table if not exists public.card_photo_presets (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null default auth.uid(),
  name text not null,
  settings jsonb not null,
  created_at timestamptz not null default now(),
  unique (user_id, name)
);
alter table public.card_photo_presets enable row level security;
do $$ begin
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='card_photo_presets' and policyname='card_photo_presets_own') then
    create policy card_photo_presets_own on public.card_photo_presets for all to authenticated
      using (user_id = auth.uid()) with check (user_id = auth.uid());
  end if;
end $$;

-- keep_originals is the one setting that can quietly destroy evidence: turned
-- off, a crop becomes the ONLY record of a card's edges. It is not blocked --
-- it's the user's storage -- but the change is recorded so "when did we stop
-- keeping originals?" has an answer.
create or replace function public.log_keep_originals_change()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  if new.keep_originals is distinct from old.keep_originals then
    insert into public.audit_log (actor, action, target, payload, result)
    values ('web', 'photo_prefs.keep_originals', new.user_id::text,
            jsonb_build_object('from', old.keep_originals, 'to', new.keep_originals),
            'ok');
  end if;
  return new;
end $$;
drop trigger if exists card_user_prefs_keep_originals_au on public.card_user_prefs;
create trigger card_user_prefs_keep_originals_au after update of keep_originals
  on public.card_user_prefs for each row execute function public.log_keep_originals_change();

-- ═══════════ 20260742000000_basis_items.sql ═══════════
-- ══════════════════════════════════════════════════════════════════════════
-- COST BASIS BREAKDOWN (Beau, 2026-07-25)
--
-- "it should be called a cost basis area... 'Total Cost Basis'... a drop down
--  or extra area that you can expand where you can add a breakdown of the
--  items that make up your cost basis... grading fees, appraisal fees, etc...
--  and the ability to make your own cost basis items. then these can be
--  edited/added later."
--
-- DESIGN: costs ACCRETE, they don't replace acquisition.
--
-- CLAUDE.md says a card's basis has exactly two sources and there is no third
-- path. That stays true. `individual_basis` still means ONE thing — what the
-- card cost to acquire — and a purchase lot still means the other. Everything
-- here is a THIRD CATEGORY, not a third source: costs capitalized into the
-- card AFTER acquisition. That is also what they are in tax terms, which is
-- why a lot-funded card can carry a grading fee without the lot's own balance
-- moving a cent.
--
--   total basis = (lot average OR individual_basis) + basis_items_total
--
-- `cards.basis_items_total` is a trigger-maintained CACHE of the child rows.
-- It exists so cardBasis() stays a pure function over a card row already in
-- memory: every money screen pages `cards` and sums that column. Making the
-- screens page a second table instead would have put a 1000-row PostgREST cap
-- (prevention rule 5) in front of every basis figure in the app.
--
-- SOLD CARDS ARE REFUSED, not restated. Profit is recorded at sale, in
-- card_sales; letting basis move afterwards silently rewrites a number that
-- may already be posted to real books. Un-sell, edit, re-sell — that path is
-- DB-enforced and leaves a trail. (A proper restatement flow, with a
-- books-drift flag, is a later job and wants Beau's decision first.)
-- ══════════════════════════════════════════════════════════════════════════

-- ── 1. what a cost line can be ────────────────────────────────────────────
-- user_id NULL = built-in, shared by everyone. A user's own kinds sit
-- alongside; they can't collide with a built-in key because the resolver
-- prefers the built-in and the index below forbids a duplicate per owner.
create table if not exists public.card_basis_item_kinds (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users(id) on delete cascade,
  key text not null check (key ~ '^[a-z0-9_]{2,40}$'),
  label text not null,
  sort int not null default 100,
  archived boolean not null default false,
  created_at timestamptz not null default now()
);
-- NULLs are never equal in a unique constraint, so a plain unique(user_id,key)
-- would let the built-in list acquire duplicates. Fold NULL to a sentinel.
create unique index if not exists card_basis_item_kinds_owner_key
  on public.card_basis_item_kinds (coalesce(user_id, '00000000-0000-0000-0000-000000000000'::uuid), key);

insert into public.card_basis_item_kinds (user_id, key, label, sort) values
  (null, 'grading_fee',        'Grading fee',              10),
  (null, 'grading_shipping',   'Shipping to grader',       20),
  (null, 'authentication',     'Authentication',           30),
  (null, 'appraisal_fee',      'Appraisal',                40),
  (null, 'sales_tax',          'Sales tax paid',           50),
  (null, 'shipping_in',        'Shipping in',              60),
  (null, 'buyers_premium',     'Buyer''s premium',         70),
  (null, 'auction_fee',        'Auction / marketplace fee',80),
  (null, 'restoration',        'Repair or restoration',    90),
  (null, 'supplies',           'Supplies (case, sleeve)', 100),
  (null, 'insurance',          'Insurance',               110),
  (null, 'other',              'Other',                   900)
on conflict do nothing;

alter table public.card_basis_item_kinds enable row level security;
do $$ begin
  -- Everyone reads the built-ins and their own; nobody sees anyone else's.
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='card_basis_item_kinds' and policyname='card_basis_item_kinds_read') then
    create policy card_basis_item_kinds_read on public.card_basis_item_kinds for select to authenticated
      using (user_id is null or user_id = auth.uid());
  end if;
  -- Own rows only for writes — the built-in list is not user-editable.
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='card_basis_item_kinds' and policyname='card_basis_item_kinds_write') then
    create policy card_basis_item_kinds_write on public.card_basis_item_kinds for all to authenticated
      using (user_id = auth.uid()) with check (user_id = auth.uid());
  end if;
end $$;

-- ── 2. the cost lines themselves ──────────────────────────────────────────
create table if not exists public.card_basis_items (
  id uuid primary key default gen_random_uuid(),
  card_id uuid not null references public.cards(id) on delete cascade,
  -- Denormalized, exactly as card_photos had to be (20260740): during a
  -- cascade delete the parent card is ALREADY GONE, so a trigger that looks
  -- the owner up from cards finds nothing.
  user_id uuid not null,
  kind_key text not null,
  -- Snapshot of the label at write time, so renaming or archiving a kind
  -- never silently relabels a historical cost line.
  label text not null,
  -- Negative is allowed: a refund, a discount or a returned grading fee is a
  -- real cost line. The TOTAL is what gets floored at zero, below.
  amount numeric(12,2) not null check (amount between -10000000 and 10000000),
  incurred_on date,
  note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists card_basis_items_card_idx on public.card_basis_items (card_id, created_at, id);
create index if not exists card_basis_items_user_idx on public.card_basis_items (user_id, created_at, id);

alter table public.card_basis_items enable row level security;
do $$ begin
  if not exists (select 1 from pg_policies where schemaname='public' and tablename='card_basis_items' and policyname='card_basis_items_own') then
    create policy card_basis_items_own on public.card_basis_items for all to authenticated
      using (user_id = auth.uid()) with check (user_id = auth.uid());
  end if;
end $$;

-- ── 3. the cached total, and the flag that keeps 0 honest ─────────────────
alter table public.cards
  add column if not exists basis_items_total numeric(12,2) not null default 0,
  -- Beau asked for cost to be optional and default to 0. That is fine as long
  -- as "I didn't say" stays distinguishable from "it genuinely cost nothing" —
  -- otherwise an un-costed card reads as a free card and shows full sale price
  -- as profit (prevention rule 4: never $0-as-fact). Screens read this flag,
  -- not the number, to decide whether to prompt.
  add column if not exists basis_entered boolean not null default false;

-- Existing rows: anything with a basis already stated, or funded by a lot,
-- counts as entered. Only genuinely blank ones get flagged.
update public.cards
   set basis_entered = true
 where basis_entered = false
   and (individual_basis is not null or purchase_lot_id is not null);

create index if not exists cards_basis_unentered_idx
  on public.cards (user_id) where basis_entered = false;

-- ── 4. keep the cache exactly equal to the rows ───────────────────────────
create or replace function public.sync_card_basis_items_total()
returns trigger language plpgsql security definer set search_path = public as $$
declare v_card uuid; v_total numeric;
begin
  v_card := coalesce(new.card_id, old.card_id);
  select coalesce(sum(amount), 0) into v_total
    from public.card_basis_items where card_id = v_card;
  -- The handshake that lets this write past guard_card_basis_total. It is
  -- transaction-local and reset immediately: a flag left set would disable the
  -- guard for the rest of the transaction (the money-core harness learned this
  -- the hard way with cardops.in_sell).
  perform set_config('cardops.in_basis', '1', true);
  update public.cards set basis_items_total = v_total where id = v_card;
  perform set_config('cardops.in_basis', '', true);
  return coalesce(new, old);
end $$;

drop trigger if exists card_basis_items_sync on public.card_basis_items;
create trigger card_basis_items_sync
  after insert or update or delete on public.card_basis_items
  for each row execute function public.sync_card_basis_items_total();

-- The cache has exactly ONE writer. Without this, a PostgREST update of
-- `cards` could set any total it liked and no screen would ever disagree.
create or replace function public.guard_card_basis_total()
returns trigger language plpgsql set search_path = public as $$
begin
  if new.basis_items_total is distinct from old.basis_items_total
     and coalesce(current_setting('cardops.in_basis', true), '') <> '1' then
    raise exception 'basis_items_total is maintained from card_basis_items — add or edit a cost line instead';
  end if;
  return new;
end $$;
drop trigger if exists cards_basis_total_guard on public.cards;
create trigger cards_basis_total_guard before update on public.cards
  for each row execute function public.guard_card_basis_total();

-- ── 5. what a cost line may not do ────────────────────────────────────────
create or replace function public.guard_card_basis_item()
returns trigger language plpgsql security definer set search_path = public as $$
declare v_owner uuid; v_status text; v_indiv numeric; v_total numeric; v_card uuid;
begin
  v_card := coalesce(new.card_id, old.card_id);
  select user_id, status, coalesce(individual_basis, 0)
    into v_owner, v_status, v_indiv
    from public.cards where id = v_card;

  -- No card = a cascade delete in flight. Let the rows go.
  if v_owner is null then return coalesce(new, old); end if;

  if tg_op <> 'DELETE' then
    -- The FK alone would accept another user's card id: FK checks bypass RLS.
    -- Same reasoning as guard_card_lot_link in 20260735.
    if new.user_id is distinct from v_owner then
      raise exception 'a cost line must belong to the same user as its card';
    end if;

    -- Resolve the kind from its KEY and stamp both label and key from what we
    -- resolved. Accepting a caller-supplied kind id would let one tenant point
    -- at another tenant's private kind row.
    if not exists (
      select 1 from public.card_basis_item_kinds
       where key = new.kind_key and (user_id is null or user_id = v_owner) and not archived
    ) then
      raise exception 'unknown or archived cost kind: %', new.kind_key;
    end if;
    if new.label is null or btrim(new.label) = '' then
      select label into new.label from public.card_basis_item_kinds
       where key = new.kind_key and (user_id is null or user_id = v_owner)
       order by user_id nulls last limit 1;
    end if;
  end if;

  -- A sold card's profit is already recorded in card_sales and may already be
  -- posted to real books. Moving its basis afterwards rewrites history in
  -- silence. Un-sell, edit, re-sell — that path exists and leaves a trail.
  if v_status = 'sold' then
    raise exception 'this card is sold — un-sell it first if its cost basis really needs to change';
  end if;

  -- Credit lines are allowed, but they may not drive total basis negative.
  select coalesce(sum(amount), 0) into v_total
    from public.card_basis_items
   where card_id = v_card and id is distinct from coalesce(new.id, old.id);
  if tg_op <> 'DELETE' then v_total := v_total + new.amount; end if;
  if v_indiv + v_total < 0 then
    raise exception 'that would make the card''s total cost basis negative (%).', v_indiv + v_total;
  end if;

  return coalesce(new, old);
end $$;

drop trigger if exists card_basis_items_guard on public.card_basis_items;
create trigger card_basis_items_guard before insert or update or delete
  on public.card_basis_items for each row execute function public.guard_card_basis_item();

-- ── 6. stating a basis marks it stated ────────────────────────────────────
-- Set on any write that names a figure, so the "no cost basis entered" list
-- empties itself as Beau fills cards in, without a second thing to remember.
create or replace function public.mark_basis_entered()
returns trigger language plpgsql set search_path = public as $$
begin
  if tg_op = 'INSERT' then
    if new.individual_basis is not null or new.purchase_lot_id is not null then
      new.basis_entered := true;
    end if;
  elsif new.individual_basis is distinct from old.individual_basis
        or new.purchase_lot_id is distinct from old.purchase_lot_id then
    if new.individual_basis is not null or new.purchase_lot_id is not null then
      new.basis_entered := true;
    end if;
  end if;
  return new;
end $$;
drop trigger if exists cards_mark_basis_entered on public.cards;
create trigger cards_mark_basis_entered before insert or update on public.cards
  for each row execute function public.mark_basis_entered();

-- Adding a cost line is also stating a basis.
create or replace function public.mark_basis_entered_from_item()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  update public.cards set basis_entered = true
   where id = new.card_id and basis_entered = false;
  return new;
end $$;
drop trigger if exists card_basis_items_mark_entered on public.card_basis_items;
create trigger card_basis_items_mark_entered after insert on public.card_basis_items
  for each row execute function public.mark_basis_entered_from_item();

-- ── 7. card_sell draws the FULL basis, acquisition + cost lines ───────────
-- Without this the breakdown would be decoration: you could record $60 of
-- grading and still book profit as if the card cost only what you paid for it.
-- The lot half is unchanged — the lot's own balance still moves by the lot
-- average alone, so `Σ(draws) = lot.total_cost` still holds.
create or replace function public.card_sell(
  p_card_id uuid, p_platform text, p_sale_price numeric, p_fees numeric,
  p_ship_income numeric, p_ship_cost numeric, p_order_ref text)
returns jsonb language plpgsql security definer set search_path = public as $$
declare
  v_card public.cards%rowtype; v_lot public.purchase_lots%rowtype;
  v_basis numeric := 0; v_acq numeric := 0; v_items numeric := 0;
  v_net numeric; v_pl numeric;
begin
  if not (public.owns_card(p_card_id) or auth.role() = 'service_role') then raise exception 'forbidden'; end if;

  select * into v_card from public.cards where id = p_card_id for update;
  if not found then raise exception 'card not found'; end if;
  if v_card.status = 'sold' then raise exception 'card already sold'; end if;
  if p_sale_price is null or p_sale_price < 0 then raise exception 'sale price required'; end if;

  v_net := coalesce(p_sale_price, 0) - coalesce(p_fees, 0) + coalesce(p_ship_income, 0) - coalesce(p_ship_cost, 0);

  perform set_config('cardops.in_sell', '1', true);

  if v_card.purchase_lot_id is not null then
    select * into v_lot from public.purchase_lots where id = v_card.purchase_lot_id for update;
    if found and v_lot.remaining_count > 0 then
      v_acq := round(v_lot.remaining_cost / v_lot.remaining_count, 2);
      insert into public.purchase_lot_adjustments
        (lot_id, kind, card_id, amount, remaining_cost_after, remaining_count_after, actor, note)
      values
        (v_lot.id, 'draw', p_card_id, -v_acq,
         v_lot.remaining_cost - v_acq, v_lot.remaining_count - 1,
         coalesce(auth.uid()::text, 'system'), 'Sale draw');
      update public.purchase_lots
        set remaining_cost = remaining_cost - v_acq, remaining_count = remaining_count - 1
        where id = v_lot.id;
    end if;
  else
    v_acq := coalesce(v_card.individual_basis, 0);
  end if;

  -- Read the rows, not the cache. The cache is what the SCREENS read; the
  -- money figure that lands in card_sales is computed from the source.
  select coalesce(sum(amount), 0) into v_items
    from public.card_basis_items where card_id = p_card_id;

  v_basis := v_acq + v_items;
  v_pl := v_net - v_basis;

  insert into public.card_sales
    (card_id, user_id, platform, sale_price, fees, shipping_income, shipping_cost, net_proceeds, basis_drawn, profit_loss, order_ref)
  values (p_card_id, v_card.user_id, p_platform, p_sale_price, p_fees, p_ship_income, p_ship_cost, v_net, v_basis, v_pl, p_order_ref);
  update public.cards set status = 'sold', sold_at = now(), basis_drawn = v_basis where id = p_card_id;

  return jsonb_build_object('net', v_net, 'basis', v_basis,
                            'acquisition', v_acq, 'cost_lines', v_items, 'profit_loss', v_pl);
end $$;

revoke all on function public.card_sell(uuid, text, numeric, numeric, numeric, numeric, text) from public;
grant execute on function public.card_sell(uuid, text, numeric, numeric, numeric, numeric, text) to authenticated, service_role;

-- ═══════════ 20260743000000_photo_bucket_limits.sql ═══════════
-- ══════════════════════════════════════════════════════════════════════════
-- CARD-PHOTOS BUCKET LIMITS (Beau, 2026-07-25)
--
-- Photos now go straight from the BROWSER to storage rather than through a
-- server action (which is what stopped booking a card from hanging on
-- "Saving…" — see next-steps step 0). That removed the accidental ceiling the
-- server-action body limit used to provide: until now a signed-in card user
-- could PUT an object of any size and any content type into this bucket.
--
-- Storage is a metered, billable resource. An unbounded write path is how one
-- careless upload becomes someone else's bill.
--
-- 25 MB is deliberately generous: the Archive quality preset caps the long
-- edge at 4000px, which lands around 3 MB, and a 12-shot grading template
-- keeps every frame separate rather than in one giant file. Nothing the app
-- produces should come close.
-- ══════════════════════════════════════════════════════════════════════════

update storage.buckets
   set file_size_limit = 26214400,   -- 25 MiB per object
       allowed_mime_types = array['image/jpeg', 'image/png', 'image/webp', 'image/heic']
 where id = 'card-photos';

-- ── finding orphans ───────────────────────────────────────────────────────
-- An object can now exist with no card_photos row: the browser's upload
-- succeeded and the recording call failed. Those bytes are invisible to the
-- storage meter (user_storage_usage sums card_photos.bytes) and to every
-- screen. The app reports the failure and offers a retry, but nothing sweeps
-- what was already abandoned, so here is the query that finds them.
--
-- Owner-only: it reads across tenants by design, which is why it is not
-- exposed to `authenticated`.
create or replace function public.card_photo_orphans()
returns table (name text, owner_segment text, bytes bigint, created_at timestamptz)
language sql stable security definer set search_path = public, storage as $$
  select o.name,
         split_part(o.name, '/', 1) as owner_segment,
         coalesce((o.metadata->>'size')::bigint, 0) as bytes,
         o.created_at
    from storage.objects o
   where o.bucket_id = 'card-photos'
     and not exists (select 1 from public.card_photos p where p.path = o.name)
     -- Give an in-flight upload time to be recorded before calling it orphaned.
     and o.created_at < now() - interval '1 hour'
   order by o.created_at desc
$$;
revoke all on function public.card_photo_orphans() from public;
do $$ begin
  if exists (select 1 from pg_roles where rolname = 'service_role') then
    execute 'grant execute on function public.card_photo_orphans() to service_role';
  end if;
end $$;
